![title](images/header.png)

Merging CEO data (phase I 2015-2020) and phase II (2015-2022) for training with calibration and validation split
-------
This notebook merges validated data from the stratified random CEO data (2015-2022) with ceo data from phase II (2015-2022)
For more information contact aurelie.shapiro@fao.org or remi.dannunzio@fao.org

this script merges multiple ceo files and data from CAFI phase I and phase II
you can use the last section to split CEO data into proportions of training and validation
in the parameters you will select your CEO clean files (from CAFI DDD eSBAE merge and clean CEO data)

#### first install libraries and packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# Set the display option to a large value to prevent text wrapping
pd.set_option('display.max_colwidth', None)

#### merge multiple CEO files and combine columns

### parameters

In [2]:
# COD COG CMR GAB EQG CAF
ISO = 'COD'

In [3]:
# clean ceo data from script 05d
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/GAB/GAB_all_ceo_1522_clean.csv')
ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/DRC/DRC_all_ceo_1522_clean.csv')
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/EQG/EQG_all_ceo_1522_clean.csv')
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/COG/COG_all_ceo_1622_clean.csv',low_memory=False)
#ceo_phase_IIa = pd.read_csv('/home/sepal-user/module_results/esbae/COG/COG_all_ceo_1522_clean.csv',low_memory=False)
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/CAR/CAR_all_ceo_1522_clean.csv',low_memory=False)
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/CMR/CMR_all_ceo_1522_clean.csv',low_memory=False)

In [4]:
ceo_phase_II.head()

,ID,plotid,sampleid,lon,lat,sample_geom,point_id,Ref_FNF_2015,Ref_Regeneration,Ref_Change_1522,Ref_Change_Type_1522,ArtFor,ArtMine,InfraR,Urb,IndFor,Other,Other_Desc,IndMine,IndAg,ArtAg,Ref_Year,Ref_NFtype,Ref_Ftype,collection,interpreted,Ref_LCover,Ref_Change_Year_1522,Def2016,Def2017,Def2018,Def2019,Def2020,Def2021,Def2022,Deg2016,Deg2017,Deg2018,Deg2019,Deg2020,Deg2021,Deg2022,Defall,Degall,Stable,NF,ISO
0,0,807773,807773,12.741453,-5.776823,POINT(12.741453 -5.776823),807773,1,NaN,1,Def,1,0,1,1,0,0,NaN,0,0,1.0,2016.0,NaN,3.0,1,1,3,Def2016,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,COD
1,1,2771794,2771794,25.879949,-3.186465,POINT(25.879949 -3.186465),2771794,1,NaN,1,Def,0,0,0,0,0,0,NaN,0,0,1.0,2020.0,NaN,3.0,1,1,3,Def2020,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,COD
2,2,2883802,2883802,25.220591,-6.717631,POINT(25.220591 -6.717631),2883802,0,non,0,NF,0,0,0,0,0,0,NaN,0,0,NaN,NaN,13.0,NaN,1,1,13,NF,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,COD
3,3,2880499,2880499,23.853181,-10.566491,POINT(23.853181 -10.566491),2880499,1,NaN,0,Stable,0,0,0,0,0,0,NaN,0,0,NaN,NaN,NaN,2.0,1,1,2,Stable,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,COD
4,4,2877893,2877893,23.572110,-10.311778,POINT(23.57211 -10.311778),2877893,1,NaN,1,Def,1,0,1,0,0,0,NaN,0,0,1.0,2021.0,NaN,2.0,1,1,2,Def2021,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,COD

In [5]:
phase_II_columns = ceo_phase_II.columns.tolist()
phase_II_columns

['ID',
 'plotid',
 'sampleid',
 'lon',
 'lat',
 'sample_geom',
 'point_id',
 'Ref_FNF_2015',
 'Ref_Regeneration',
 'Ref_Change_1522',
 'Ref_Change_Type_1522',
 'ArtFor',
 'ArtMine',
 'InfraR',
 'Urb',
 'IndFor',
 'Other',
 'Other_Desc',
 'IndMine',
 'IndAg',
 'ArtAg',
 'Ref_Year',
 'Ref_NFtype',
 'Ref_Ftype',
 'collection',
 'interpreted',
 'Ref_LCover',
 'Ref_Change_Year_1522',
 'Def2016',
 'Def2017',
 'Def2018',
 'Def2019',
 'Def2020',
 'Def2021',
 'Def2022',
 'Deg2016',
 'Deg2017',
 'Deg2018',
 'Deg2019',
 'Deg2020',
 'Deg2021',
 'Deg2022',
 'Defall',
 'Degall',
 'Stable',
 'NF',
 'ISO']

In [7]:
#ceo_phase_II.drop(columns=['sampleid', 'email', 'flagged', 'collection_time', 'analysis_duration'], inplace=True)

In [8]:
# output file names
# CEO phase I and phase II data
ceo_phase_I_II_out =  '/home/sepal-user/module_results/esbae/DRC/DRC_ceo_1522_phase_I_II.csv'
# stable data split into training and validation
ceo_phase_I_II_stable_out_train = '/home/sepal-user/module_results/esbae/DRC/DRC_all_ceo_1522_phaseI_II_stable_train.csv'
ceo_phase_I_II_stable_out_val = '/home/sepal-user/module_results/esbae/DRC/DRC_all_ceo_1522_phaseI_II_stable_val.csv'

#### CEO phase I data (2015-2020)
##### this file is downloaded from git: https://github.com/aurelgrooves/CAFI_DDD

In [9]:
ceo_phase_I = pd.read_csv('/home/sepal-user/CAFI_DDD/CAFI_all_ceo_validation_2015_2020_uniqueID.csv', low_memory=False)
ceo_phase_I.reset_index(inplace=True)
phase_I_columns = ceo_phase_I.columns.tolist()
phase_I_columns

['index',
 'plotid_orig',
 'CEO_PLOTID',
 'lon',
 'lat',
 'ISO',
 'CEO_Ref_Code',
 'Ref_FNF_2015',
 'Ref_LCover',
 'Ref_Change_Type_1520',
 'Ref_Year',
 'countDrivers',
 'InfraR',
 'Urb',
 'ArtAg',
 'IndAg',
 'ArtFor',
 'IndFor',
 'ArtMin',
 'IndMin',
 'Other',
 'Source',
 'Ref_Change_Year',
 'Change_Bin',
 'UniqueID']

In [10]:
ceo_phase_I.head()

,index,plotid_orig,CEO_PLOTID,lon,lat,ISO,CEO_Ref_Code,Ref_FNF_2015,Ref_LCover,Ref_Change_Type_1520,Ref_Year,countDrivers,InfraR,Urb,ArtAg,IndAg,ArtFor,IndFor,ArtMin,IndMin,Other,Source,Ref_Change_Year,Change_Bin,UniqueID
0,0,171,NaN,24.043094,6.731301,CAF,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,306
1,1,140,NaN,18.704676,8.068803,CAF,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,307
2,2,173,NaN,13.502083,6.592511,CMR,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,308
3,3,174,NaN,23.944998,7.158989,CAF,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,309
4,4,158,NaN,13.697197,8.096830,CMR,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,310

In [11]:
ceo_phase_I['ISO'].value_counts(dropna=False)

ISO
COD    6411
CMR    2442
CAF    2325
GAB    1124
COG     686
EQG     127
Name: count, dtype: int64

In [12]:
ceo_phase_I_ISO = ceo_phase_I[ceo_phase_I['ISO'] == ISO]

In [13]:
# validation proportion
split = 0.3

### end of parameters

In [14]:
# number of validated points
len(ceo_phase_II)

13147

In [15]:
# number of validated points
len(ceo_phase_I_ISO)

6411

#### merge with phase I data (2015-2020)

In [16]:
data_frames =[ceo_phase_I_ISO, ceo_phase_II]
# Source file names corresponding to each data frame
source_file = ['phase_I', 'phase_II']  # Replace with your file names

# Merge data frames and add a new column for source file name
merged_ceo = pd.concat([df.assign(sampling=source_file) for df, source_file in zip(data_frames, source_file)], ignore_index=True)

In [17]:
# Print or use the merged data frame
merged_ceo.reset_index(inplace=True)
merged_I_columns = merged_ceo.columns.tolist()
merged_I_columns

['level_0',
 'index',
 'plotid_orig',
 'CEO_PLOTID',
 'lon',
 'lat',
 'ISO',
 'CEO_Ref_Code',
 'Ref_FNF_2015',
 'Ref_LCover',
 'Ref_Change_Type_1520',
 'Ref_Year',
 'countDrivers',
 'InfraR',
 'Urb',
 'ArtAg',
 'IndAg',
 'ArtFor',
 'IndFor',
 'ArtMin',
 'IndMin',
 'Other',
 'Source',
 'Ref_Change_Year',
 'Change_Bin',
 'UniqueID',
 'sampling',
 'ID',
 'plotid',
 'sampleid',
 'sample_geom',
 'point_id',
 'Ref_Regeneration',
 'Ref_Change_1522',
 'Ref_Change_Type_1522',
 'ArtMine',
 'Other_Desc',
 'IndMine',
 'Ref_NFtype',
 'Ref_Ftype',
 'collection',
 'interpreted',
 'Ref_Change_Year_1522',
 'Def2016',
 'Def2017',
 'Def2018',
 'Def2019',
 'Def2020',
 'Def2021',
 'Def2022',
 'Deg2016',
 'Deg2017',
 'Deg2018',
 'Deg2019',
 'Deg2020',
 'Deg2021',
 'Deg2022',
 'Defall',
 'Degall',
 'Stable',
 'NF']

In [18]:
column_names = merged_ceo.columns.tolist()
# Print the list of column names
print(column_names)

['level_0', 'index', 'plotid_orig', 'CEO_PLOTID', 'lon', 'lat', 'ISO', 'CEO_Ref_Code', 'Ref_FNF_2015', 'Ref_LCover', 'Ref_Change_Type_1520', 'Ref_Year', 'countDrivers', 'InfraR', 'Urb', 'ArtAg', 'IndAg', 'ArtFor', 'IndFor', 'ArtMin', 'IndMin', 'Other', 'Source', 'Ref_Change_Year', 'Change_Bin', 'UniqueID', 'sampling', 'ID', 'plotid', 'sampleid', 'sample_geom', 'point_id', 'Ref_Regeneration', 'Ref_Change_1522', 'Ref_Change_Type_1522', 'ArtMine', 'Other_Desc', 'IndMine', 'Ref_NFtype', 'Ref_Ftype', 'collection', 'interpreted', 'Ref_Change_Year_1522', 'Def2016', 'Def2017', 'Def2018', 'Def2019', 'Def2020', 'Def2021', 'Def2022', 'Deg2016', 'Deg2017', 'Deg2018', 'Deg2019', 'Deg2020', 'Deg2021', 'Deg2022', 'Defall', 'Degall', 'Stable', 'NF']

In [19]:
#drop columns
merged_ceo = merged_ceo.drop(['level_0','index','ID'], axis=1)
#merged_ceo = merged_ceo.rename(columns={'Unnamed: 0': 'index'})

In [20]:
# Create a new column 'Stable' with initial value 0
merged_ceo['Stable_Forest'] = 0

# Set 'Stable' to 1 where either 'Ref_Change_Type_1520' or 'Ref_Change_Type_1522' is 'Stable'
merged_ceo.loc[(merged_ceo['Ref_Change_Type_1520'] == 'Stable') | (merged_ceo['Ref_Change_Type_1522'] == 'Stable'), 'Stable_Forest'] = 1

# Display value counts of 'Stable' column
print(merged_ceo['Stable_Forest'].value_counts(dropna=False))

Stable_Forest
0    12484
1     7074
Name: count, dtype: int64

In [21]:
# Create a new column 'Ref Change Type' with initial value 0
merged_ceo['Ref_Change_Type'] = 0

merged_ceo['Ref_Change_Type'] = merged_ceo['Ref_Change_Type_1520'].fillna(merged_ceo['Ref_Change_Type_1522'])

# Display the DataFrame
print(merged_ceo['Ref_Change_Type'].value_counts(dropna=False))

Ref_Change_Type
NF        8785
Stable    7074
Def       2662
Deg       1037
Name: count, dtype: int64

In [22]:
merged_ceo['Ref_LCover'].value_counts(dropna=False)

Ref_LCover
16    4027
1     3302
4     2902
13    2389
3     2092
2     1325
9      776
12     718
15     694
19     433
18     240
11     221
14     162
17     133
8      129
10      10
7        5
Name: count, dtype: int64

In [23]:
merged_ceo['Change_Bin'] = merged_ceo['Change_Bin'].fillna(0).where(merged_ceo['Stable'] == 1, 1)
merged_ceo['Change_Bin'].value_counts(dropna=False)

Change_Bin
1.0    13960
0.0     5598
Name: count, dtype: int64

In [24]:
#create a new column for forest:1, non-forest:2, water: 3
# Define the conditions
conditions = [
    (merged_ceo['Ref_LCover'] >= 1) & (merged_ceo['Ref_LCover'] <= 11),
    (merged_ceo['Ref_LCover'] >= 12) & (merged_ceo['Ref_LCover'] <= 17),
    (merged_ceo['Ref_LCover'] == 18)
]

# Define the values to assign for each condition
values = [1, 2, 3]

# Use numpy.select() to assign values based on conditions
merged_ceo['Ref_FNFW'] = np.select(conditions, values, default=np.nan)

# Print the DataFrame with the new column
merged_ceo.head()

,plotid_orig,CEO_PLOTID,lon,lat,ISO,CEO_Ref_Code,Ref_FNF_2015,Ref_LCover,Ref_Change_Type_1520,Ref_Year,countDrivers,InfraR,Urb,ArtAg,IndAg,ArtFor,IndFor,ArtMin,IndMin,Other,Source,Ref_Change_Year,Change_Bin,UniqueID,sampling,plotid,sampleid,sample_geom,point_id,Ref_Regeneration,Ref_Change_1522,Ref_Change_Type_1522,ArtMine,Other_Desc,IndMine,Ref_NFtype,Ref_Ftype,collection,interpreted,Ref_Change_Year_1522,Def2016,Def2017,Def2018,Def2019,Def2020,Def2021,Def2022,Deg2016,Deg2017,Deg2018,Deg2019,Deg2020,Deg2021,Deg2022,Defall,Degall,Stable,NF,Stable_Forest,Ref_Change_Type,Ref_FNFW
0,235.0,NaN,28.259606,0.532117,COD,102.0,1,1,Deg,2018.0,2.0,0,1,0.0,0,1,0,0.0,0.0,0,ceo,Deg2018,1.0,106.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Deg,1.0
1,295.0,NaN,25.461983,-0.454233,COD,104.0,1,1,Deg,2020.0,1.0,0,0,0.0,0,1,0,0.0,0.0,0,ceo,Deg2020,1.0,107.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Deg,1.0
2,57.0,NaN,22.040749,3.897296,COD,1.0,1,1,Stable,NaN,0.0,0,0,0.0,0,0,0,0.0,0.0,0,ceo,Stable,1.0,110.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Stable,1.0
3,23.0,NaN,28.895614,2.056917,COD,1.0,1,1,Stable,NaN,0.0,0,0,0.0,0,0,0,0.0,0.0,0,ceo,Stable,1.0,112.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Stable,1.0
4,19.0,NaN,17.712936,-1.380486,COD,1.0,1,1,Stable,NaN,0.0,0,0,0.0,0,0,0,0.0,0.0,0,ceo,Stable,1.0,113.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Stable,1.0

In [25]:
merged_ceo['Ref_FNFW'].value_counts(dropna=False)

Ref_FNFW
1.0    10762
2.0     8123
NaN      433
3.0      240
Name: count, dtype: int64

#### split stable data into training and calibration for land cover classification

In [26]:
# Filter rows where 'Stable' equals 1
stable_rows = merged_ceo[(merged_ceo['Stable_Forest'] == 1) | (merged_ceo['NF'] == 1)]

In [27]:
# Define an empty DataFrame to store the split data
split_data = pd.DataFrame()

# Iterate over unique values in 'landcover' column
for landcover_value in stable_rows['Ref_LCover'].unique():
    # Filter rows for current landcover value
    landcover_rows = stable_rows[stable_rows['Ref_LCover'] == landcover_value]
    
    # Check if there is enough data to split
    if len(landcover_rows) > 1:
        # Split data into training and validation sets
        train_data, val_data = train_test_split(landcover_rows, test_size=split, random_state=42)
        
        # Add 'Split' column and assign 'train' or 'val' based on split
        train_data['split'] = 'train'
        val_data['split'] = 'val'
        
        # Concatenate data to the split_data DataFrame
        split_data = pd.concat([split_data, train_data, val_data], ignore_index=True)
    else:
        # Not enough data for splitting, assign all data as calibration data
        landcover_rows['split'] = 'calibration'
        split_data = pd.concat([split_data, landcover_rows], ignore_index=True)

split_data.head()

,plotid_orig,CEO_PLOTID,lon,lat,ISO,CEO_Ref_Code,Ref_FNF_2015,Ref_LCover,Ref_Change_Type_1520,Ref_Year,countDrivers,InfraR,Urb,ArtAg,IndAg,ArtFor,IndFor,ArtMin,IndMin,Other,Source,Ref_Change_Year,Change_Bin,UniqueID,sampling,plotid,sampleid,sample_geom,point_id,Ref_Regeneration,Ref_Change_1522,Ref_Change_Type_1522,ArtMine,Other_Desc,IndMine,Ref_NFtype,Ref_Ftype,collection,interpreted,Ref_Change_Year_1522,Def2016,Def2017,Def2018,Def2019,Def2020,Def2021,Def2022,Deg2016,Deg2017,Deg2018,Deg2019,Deg2020,Deg2021,Deg2022,Defall,Degall,Stable,NF,Stable_Forest,Ref_Change_Type,Ref_FNFW,split
0,NaN,NaN,27.216770,2.941125,COD,NaN,1,1,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,NaN,0.0,NaN,phase_II,2501785.0,2501785.0,POINT(27.21677 2.941125),2501785.0,NaN,0.0,Stable,0.0,NaN,0.0,NaN,1.0,3.0,1.0,Stable,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,Stable,1.0,train
1,301657.0,9918,29.057849,-4.870980,COD,1.0,1,1,Stable,NaN,0.0,0,0,0.0,0,0,0,0.0,0.0,0,ceo,Stable,1.0,10552.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Stable,1.0,train
2,0.0,,22.315901,-8.374138,COD,1.0,1,1,Stable,NaN,0.0,0,0,0.0,0,0,0,0.0,0.0,0,TMF,Stable,1.0,12736.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Stable,1.0,train
3,NaN,NaN,25.949805,1.474014,COD,NaN,1,1,NaN,NaN,NaN,0,0,NaN,0,0,0,NaN,NaN,0,NaN,NaN,0.0,NaN,phase_II,2471551.0,2471551.0,POINT(25.949805 1.474014),2471551.0,NaN,0.0,Stable,0.0,NaN,0.0,NaN,1.0,3.0,1.0,Stable,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,Stable,1.0,train
4,0.0,,27.519306,-1.495021,COD,1.0,1,1,Stable,NaN,0.0,0,0,0.0,0,0,0,0.0,0.0,0,TMF,Stable,1.0,12958.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Stable,1.0,train

In [28]:
# Print summaries
split_data['split'].value_counts(dropna=False)

split
train    9352
val      4019
Name: count, dtype: int64

In [29]:
pd.pivot_table(split_data,values='point_id',index=['Ref_LCover'],columns=['split'],aggfunc="count")

split       train   val
Ref_LCover
1             878   361
2             666   286
3             505   216
4            1546   668
7               2     1
8              64    25
9             224    86
10              1     2
11             47    20
12            494   213
13           1125   483
14             88    39
15            158    68
16           2348  1007
17             28    13
18            163    70

#### Export

In [30]:
# export merged phase I and II data
all_ceo_data =  ceo_phase_I_II_out
merged_ceo.to_csv(all_ceo_data,index_label='ID')

In [31]:
# export only stable data with training and validation split
split_data_train = split_data[(split_data['split'] == 'train')]
split_data.to_csv(ceo_phase_I_II_stable_out_train,index_label='ID')

In [32]:
# export only stable data with training and validation split
split_data_val = split_data[(split_data['split'] == 'val')]
split_data_val.to_csv(ceo_phase_I_II_stable_out_val,index_label='ID')