![title](images/header.png)

Merging CEO data (phase I 2015-2020) and phase II (2015-2022) for training with calibration and validation split
-------
This notebook merges validated data from the stratified random CEO data (2015-2022) with ceo data from phase II (2015-2022)
For more information contact aurelie.shapiro@fao.org or remi.dannunzio@fao.org

this script merges multiple ceo files and data from CAFI phase I and phase II
you can use the last section to split CEO data into proportions of training and validation
in the parameters you will select your CEO clean files (from CAFI DDD eSBAE merge and clean CEO data)

#### first install libraries and packages

In [310]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# Set the display option to a large value to prevent text wrapping
pd.set_option('display.max_colwidth', None)

#### merge multiple CEO files and combine columns

### parameters

In [389]:
# COD COG CMR GAB EQG CAF
ISO = 'CMR'

In [390]:
# clean ceo data from script 05d
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/GAB/GAB_all_ceo_1522_clean.csv')
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/DRC/DRC_all_ceo_1522_clean.csv')
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/EQG/EQG_all_ceo_1522_clean.csv')
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/COG/COG_all_ceo_1522_1622_clean.csv',low_memory=False)
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/CAR/CAR_all_ceo_1522_clean.csv',low_memory=False)
ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/CMR/CMR_all_ceo_1522_clean.csv',low_memory=False)

In [391]:
ceo_phase_II.head()

,ID,plotid,sampleid,lon,lat,sample_geom,point_id,Ref_FNF_2015,Ref_Regeneration,Ref_Change_1522,Ref_Change_Type_1522,ArtFor,ArtMine,InfraR,Urb,IndFor,Other,Other_Desc,IndMine,IndAg,ArtAg,Ref_Year,Ref_NFtype,Ref_Ftype,collection,interpreted,Ref_LCover,Ref_Change_Year_1522,Def2016,Def2017,Def2018,Def2019,Def2020,Def2021,Def2022,Deg2016,Deg2017,Deg2018,Deg2019,Deg2020,Deg2021,Deg2022,Defall,Degall,Stable,NF,ISO
0,0,21086,21086,9.965217,5.555808,POINT(9.965217 5.555808),21086,0,non,0,NF,0,0,0,0,0,0,NaN,0,0,NaN,NaN,15.0,NaN,1,1,15,NF,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,CMR
1,1,21466,21466,10.010548,5.507766,POINT(10.010548 5.507766),21466,0,non,0,NF,0,0,0,0,0,0,NaN,0,0,NaN,NaN,15.0,NaN,1,1,15,NF,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,CMR
2,2,27151,27151,10.572640,5.449557,POINT(10.57264 5.449557),27151,1,NaN,0,Stable,0,0,0,0,0,0,NaN,0,0,NaN,NaN,NaN,3.0,1,1,3,Stable,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,CMR
3,3,27628,27628,10.507876,5.228925,POINT(10.507876 5.228925),27628,0,non,0,NF,0,0,0,0,0,0,NaN,0,0,NaN,NaN,15.0,NaN,1,1,15,NF,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,CMR
4,4,28491,28491,10.413428,4.873860,POINT(10.413428 4.87386),28491,1,NaN,0,Stable,0,0,0,0,0,0,NaN,0,0,NaN,NaN,NaN,1.0,1,1,1,Stable,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,CMR

In [392]:
phase_II_columns = ceo_phase_II.columns.tolist()
phase_II_columns

['ID',
 'plotid',
 'sampleid',
 'lon',
 'lat',
 'sample_geom',
 'point_id',
 'Ref_FNF_2015',
 'Ref_Regeneration',
 'Ref_Change_1522',
 'Ref_Change_Type_1522',
 'ArtFor',
 'ArtMine',
 'InfraR',
 'Urb',
 'IndFor',
 'Other',
 'Other_Desc',
 'IndMine',
 'IndAg',
 'ArtAg',
 'Ref_Year',
 'Ref_NFtype',
 'Ref_Ftype',
 'collection',
 'interpreted',
 'Ref_LCover',
 'Ref_Change_Year_1522',
 'Def2016',
 'Def2017',
 'Def2018',
 'Def2019',
 'Def2020',
 'Def2021',
 'Def2022',
 'Deg2016',
 'Deg2017',
 'Deg2018',
 'Deg2019',
 'Deg2020',
 'Deg2021',
 'Deg2022',
 'Defall',
 'Degall',
 'Stable',
 'NF',
 'ISO']

In [394]:
# output file names
# CEO phase I and phase II data
ceo_phase_I_II_out =  '/home/sepal-user/module_results/esbae/CMR/CMR_ceo_1522_phase_I_II.csv'
ceo_phase_I_II_stable_out = '/home/sepal-user/module_results/esbae/CMR/CMR_ceo_1522_phase_I_II_stable.csv'
# stable data split into training and validation
ceo_phase_I_II_stable_out_train = '/home/sepal-user/module_results/esbae/CMR/CMR_all_ceo_1522_phaseI_II_stable_train.csv'
ceo_phase_I_II_stable_out_val = '/home/sepal-user/module_results/esbae/CMR/CMR_all_ceo_1522_phaseI_II_stable_val.csv'

#### CEO phase I data (2015-2020)
##### this file is downloaded from git: https://github.com/aurelgrooves/CAFI_DDD

In [395]:
ceo_phase_I = pd.read_csv('/home/sepal-user/CAFI_DDD/CAFI_all_ceo_validation_2015_2020_uniqueID.csv', low_memory=False)
ceo_phase_I.reset_index(inplace=True)
phase_I_columns = ceo_phase_I.columns.tolist()
phase_I_columns

['index',
 'plotid_orig',
 'CEO_PLOTID',
 'lon',
 'lat',
 'ISO',
 'CEO_Ref_Code',
 'Ref_FNF_2015',
 'Ref_LCover',
 'Ref_Change_Type_1520',
 'Ref_Year_1520',
 'countDrivers',
 'InfraR',
 'Urb',
 'ArtAg',
 'IndAg',
 'ArtFor',
 'IndFor',
 'ArtMine',
 'IndMine',
 'Other',
 'Source',
 'Ref_Change_Year_1520',
 'Change_Bin_1520',
 'UniqueID']

In [396]:
ceo_phase_I.head()

,index,plotid_orig,CEO_PLOTID,lon,lat,ISO,CEO_Ref_Code,Ref_FNF_2015,Ref_LCover,Ref_Change_Type_1520,Ref_Year_1520,countDrivers,InfraR,Urb,ArtAg,IndAg,ArtFor,IndFor,ArtMine,IndMine,Other,Source,Ref_Change_Year_1520,Change_Bin_1520,UniqueID
0,0,171,NaN,24.043094,6.731301,CAF,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,306
1,1,140,NaN,18.704676,8.068803,CAF,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,307
2,2,173,NaN,13.502083,6.592511,CMR,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,308
3,3,174,NaN,23.944998,7.158989,CAF,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,309
4,4,158,NaN,13.697197,8.096830,CMR,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,310

In [397]:
ceo_phase_I['ISO'].value_counts(dropna=False)

ISO
COD    6411
CMR    2442
CAF    2325
GAB    1124
COG     686
EQG     127
Name: count, dtype: int64

In [398]:
ceo_phase_I_ISO = ceo_phase_I[ceo_phase_I['ISO'] == ISO]
len(ceo_phase_I_ISO)

2442

In [399]:
ceo_phase_I_ISO['Ref_LCover'].value_counts(dropna=False)

Ref_LCover
1     597
16    349
15    313
3     290
13    229
12    161
9     100
4      80
17     69
11     69
2      53
8      47
7      36
14     32
10     12
18      5
Name: count, dtype: int64

In [400]:
ceo_phase_I_ISO['ArtAg'].value_counts(dropna=False)

ArtAg
0    1894
1     548
Name: count, dtype: int64

In [401]:
# validation proportion
split = 0.3

### end of parameters

In [402]:
# number of validated points
len(ceo_phase_II)

6733

In [403]:
# number of validated points
len(ceo_phase_I_ISO)

2442

In [404]:
ceo_phase_I['interpreted'] = 1

In [405]:
#drop columns
ceo_phase_II = ceo_phase_II.drop(['Def2016','Def2017','Def2018',
'Def2019','Def2020','Def2021','Def2022','Deg2016','Deg2017','Deg2018',
'Deg2019','Deg2020','Deg2021','Deg2022', 'Defall', 'Degall','Stable','NF'], axis=1)

#### merge with phase I data (2015-2020)

In [406]:
data_frames =[ceo_phase_I_ISO, ceo_phase_II]
# Source file names corresponding to each data frame
source_file = ['phase_I', 'phase_II']  # Replace with your file names

# Merge data frames and add a new column for source file name
merged_ceo = pd.concat([df.assign(sampling=source_file) for df, source_file in zip(data_frames, source_file)], ignore_index=True)

In [407]:
# Print or use the merged data frame
merged_ceo.reset_index(inplace=True)
merged_I_columns = merged_ceo.columns.tolist()
merged_I_columns

['level_0',
 'index',
 'plotid_orig',
 'CEO_PLOTID',
 'lon',
 'lat',
 'ISO',
 'CEO_Ref_Code',
 'Ref_FNF_2015',
 'Ref_LCover',
 'Ref_Change_Type_1520',
 'Ref_Year_1520',
 'countDrivers',
 'InfraR',
 'Urb',
 'ArtAg',
 'IndAg',
 'ArtFor',
 'IndFor',
 'ArtMine',
 'IndMine',
 'Other',
 'Source',
 'Ref_Change_Year_1520',
 'Change_Bin_1520',
 'UniqueID',
 'sampling',
 'ID',
 'plotid',
 'sampleid',
 'sample_geom',
 'point_id',
 'Ref_Regeneration',
 'Ref_Change_1522',
 'Ref_Change_Type_1522',
 'Other_Desc',
 'Ref_Year',
 'Ref_NFtype',
 'Ref_Ftype',
 'collection',
 'interpreted',
 'Ref_Change_Year_1522']

In [408]:
column_names = merged_ceo.columns.tolist()
# Print the list of column names
print(column_names)

['level_0', 'index', 'plotid_orig', 'CEO_PLOTID', 'lon', 'lat', 'ISO', 'CEO_Ref_Code', 'Ref_FNF_2015', 'Ref_LCover', 'Ref_Change_Type_1520', 'Ref_Year_1520', 'countDrivers', 'InfraR', 'Urb', 'ArtAg', 'IndAg', 'ArtFor', 'IndFor', 'ArtMine', 'IndMine', 'Other', 'Source', 'Ref_Change_Year_1520', 'Change_Bin_1520', 'UniqueID', 'sampling', 'ID', 'plotid', 'sampleid', 'sample_geom', 'point_id', 'Ref_Regeneration', 'Ref_Change_1522', 'Ref_Change_Type_1522', 'Other_Desc', 'Ref_Year', 'Ref_NFtype', 'Ref_Ftype', 'collection', 'interpreted', 'Ref_Change_Year_1522']

In [409]:
#drop columns
merged_ceo = merged_ceo.drop(['level_0','index','ID'], axis=1)

In [410]:
# Create a new column 'Stable' with initial value 0
merged_ceo['Stable_Forest'] = 0

# Set 'Stable' to 1 where either 'Ref_Change_Type_1520' or 'Ref_Change_Type_1522' is 'Stable'
merged_ceo.loc[(merged_ceo['Ref_Change_Type_1520'] == 'Stable') | (merged_ceo['Ref_Change_Type_1522'] == 'Stable'), 'Stable_Forest'] = 1

# Display value counts of 'Stable' column
print(merged_ceo['Stable_Forest'].value_counts(dropna=False))

Stable_Forest
0    5826
1    3349
Name: count, dtype: int64

In [411]:
# Create a new column 'Ref Change Type' with initial value 0
merged_ceo['Ref_Change_Type'] = 0

In [412]:
merged_ceo['Ref_Change_Type'] = merged_ceo['Ref_Change_Type_1520'].fillna(merged_ceo['Ref_Change_Type_1522'])

In [413]:
print(merged_ceo['Ref_Change_Type'].value_counts(dropna=False))

Ref_Change_Type
NF        4884
Stable    3349
Def        556
Deg        386
Name: count, dtype: int64

In [414]:
merged_ceo['Ref_Change_Bin'] = merged_ceo['Ref_Change_Type'].apply(lambda x:1 if x in ['Def','Deg'] else 0)
merged_ceo['Ref_Change_Bin'].value_counts(dropna=False)

Ref_Change_Bin
0    8233
1     942
Name: count, dtype: int64

In [415]:
merged_ceo['Ref_LCover'].value_counts(dropna=False)

Ref_LCover
12    2591
1     1761
15     881
13     656
9      647
16     638
3      600
11     488
4      313
17     192
2      121
8      101
14      65
7       51
10      50
18      20
Name: count, dtype: int64

In [416]:
#create a new column for forest:1, non-forest:2, water: 3
# Define the conditions
conditions = [
    (merged_ceo['Ref_LCover'] >= 1) & (merged_ceo['Ref_LCover'] <= 11),
    (merged_ceo['Ref_LCover'] >= 12) & (merged_ceo['Ref_LCover'] <= 17)|(merged_ceo['Ref_LCover'] == 19) ,
    (merged_ceo['Ref_LCover'] == 18)
]

# Define the values to assign for each condition
values = [1, 2, 3]

# Use numpy.select() to assign values based on conditions
merged_ceo['Ref_FNFW'] = np.select(conditions, values, default=np.nan)
merged_ceo['Ref_FNFW'] = merged_ceo['Ref_FNFW'].astype(int)
# Print the DataFrame with the new column
merged_ceo.head()

,plotid_orig,CEO_PLOTID,lon,lat,ISO,CEO_Ref_Code,Ref_FNF_2015,Ref_LCover,Ref_Change_Type_1520,Ref_Year_1520,countDrivers,InfraR,Urb,ArtAg,IndAg,ArtFor,IndFor,ArtMine,IndMine,Other,Source,Ref_Change_Year_1520,Change_Bin_1520,UniqueID,sampling,plotid,sampleid,sample_geom,point_id,Ref_Regeneration,Ref_Change_1522,Ref_Change_Type_1522,Other_Desc,Ref_Year,Ref_NFtype,Ref_Ftype,collection,interpreted,Ref_Change_Year_1522,Stable_Forest,Ref_Change_Type,Ref_Change_Bin,Ref_FNFW
0,173.0,NaN,13.502083,6.592511,CMR,12.0,0,12,NF,NaN,0.0,0,0,0.0,0,0,0,0,0,0,ceo,NF,0.0,308.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NF,0,2
1,158.0,NaN,13.697197,8.096830,CMR,12.0,0,12,NF,NaN,0.0,0,0,0.0,0,0,0,0,0,0,ceo,NF,0.0,310.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NF,0,2
2,211.0,NaN,9.836957,4.558097,CMR,104.0,1,1,Deg,2020.0,3.0,1,0,1.0,0,1,0,0,0,0,ceo,Deg2020,1.0,108.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Deg,1,1
3,4.0,NaN,11.127297,3.666070,CMR,1.0,1,1,Stable,NaN,0.0,0,0,0.0,0,0,0,0,0,0,ceo,Stable,0.0,135.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Stable,0,1
4,304.0,NaN,13.264389,4.078935,CMR,1.0,1,1,Stable,NaN,0.0,0,0,0.0,0,0,0,0,0,0,ceo,Stable,0.0,145.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Stable,0,1

In [417]:
merged_ceo['Ref_FNFW'].value_counts(dropna=False)

Ref_FNFW
2    5023
1    4132
3      20
Name: count, dtype: int64

#### split stable data into training and calibration for land cover classification

In [418]:
# Filter rows where 'Stable' equals 1
stable_rows = merged_ceo[(merged_ceo['Ref_Change_Bin'] == 0)]

In [419]:
stable_rows.head()

,plotid_orig,CEO_PLOTID,lon,lat,ISO,CEO_Ref_Code,Ref_FNF_2015,Ref_LCover,Ref_Change_Type_1520,Ref_Year_1520,countDrivers,InfraR,Urb,ArtAg,IndAg,ArtFor,IndFor,ArtMine,IndMine,Other,Source,Ref_Change_Year_1520,Change_Bin_1520,UniqueID,sampling,plotid,sampleid,sample_geom,point_id,Ref_Regeneration,Ref_Change_1522,Ref_Change_Type_1522,Other_Desc,Ref_Year,Ref_NFtype,Ref_Ftype,collection,interpreted,Ref_Change_Year_1522,Stable_Forest,Ref_Change_Type,Ref_Change_Bin,Ref_FNFW
0,173.0,NaN,13.502083,6.592511,CMR,12.0,0,12,NF,NaN,0.0,0,0,0.0,0,0,0,0,0,0,ceo,NF,0.0,308.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NF,0,2
1,158.0,NaN,13.697197,8.096830,CMR,12.0,0,12,NF,NaN,0.0,0,0,0.0,0,0,0,0,0,0,ceo,NF,0.0,310.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NF,0,2
3,4.0,NaN,11.127297,3.666070,CMR,1.0,1,1,Stable,NaN,0.0,0,0,0.0,0,0,0,0,0,0,ceo,Stable,0.0,135.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Stable,0,1
4,304.0,NaN,13.264389,4.078935,CMR,1.0,1,1,Stable,NaN,0.0,0,0,0.0,0,0,0,0,0,0,ceo,Stable,0.0,145.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Stable,0,1
5,186.0,NaN,11.827444,2.375999,CMR,1.0,1,1,Stable,NaN,0.0,0,0,0.0,0,0,0,0,0,0,ceo,Stable,0.0,151.0,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Stable,0,1

In [420]:
# Define an empty DataFrame to store the split data
split_data = pd.DataFrame()

# Iterate over unique values in 'landcover' column
for landcover_value in stable_rows['Ref_LCover'].unique():
    # Filter rows for current landcover value
    landcover_rows = stable_rows[stable_rows['Ref_LCover'] == landcover_value]
    
    # Check if there is enough data to split
    if len(landcover_rows) > 1:
        # Split data into training and validation sets
        train_data, val_data = train_test_split(landcover_rows, test_size=split, random_state=42)
        
        # Add 'Split' column and assign 'train' or 'val' based on split
        train_data['split'] = 'train'
        val_data['split'] = 'val'
        
        # Concatenate data to the split_data DataFrame
        split_data = pd.concat([split_data, train_data, val_data], ignore_index=True)
    else:
        # Not enough data for splitting, assign all data as calibration data
        landcover_rows['split'] = 'train'
        split_data = pd.concat([split_data, landcover_rows], ignore_index=True)

split_data.head()

,plotid_orig,CEO_PLOTID,lon,lat,ISO,CEO_Ref_Code,Ref_FNF_2015,Ref_LCover,Ref_Change_Type_1520,Ref_Year_1520,countDrivers,InfraR,Urb,ArtAg,IndAg,ArtFor,IndFor,ArtMine,IndMine,Other,Source,Ref_Change_Year_1520,Change_Bin_1520,UniqueID,sampling,plotid,sampleid,sample_geom,point_id,Ref_Regeneration,Ref_Change_1522,Ref_Change_Type_1522,Other_Desc,Ref_Year,Ref_NFtype,Ref_Ftype,collection,interpreted,Ref_Change_Year_1522,Stable_Forest,Ref_Change_Type,Ref_Change_Bin,Ref_FNFW,split
0,NaN,NaN,14.706329,8.000796,CMR,NaN,0,12,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,NaN,NaN,phase_II,1192635.0,1192635.0,POINT(14.706329 8.000796),397859.0,non,0.0,NF,NaN,NaN,12.0,NaN,2.0,1.0,NF,0,NF,0,2,train
1,NaN,NaN,11.788624,6.542424,CMR,NaN,0,12,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,NaN,NaN,phase_II,1182548.0,1182548.0,POINT(11.788624 6.542424),173213.0,non,0.0,NF,NaN,NaN,12.0,NaN,2.0,1.0,NF,0,NF,0,2,train
2,NaN,NaN,11.971233,7.155649,CMR,NaN,0,12,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,NaN,NaN,phase_II,997063.0,997063.0,POINT(11.971233 7.155649),192654.0,non,0.0,NF,NaN,NaN,12.0,NaN,2.0,1.0,NF,0,NF,0,2,train
3,NaN,NaN,14.276173,6.818064,CMR,NaN,0,12,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,NaN,NaN,phase_II,945445.0,945445.0,POINT(14.276173 6.818064),392357.0,non,0.0,NF,NaN,NaN,12.0,NaN,2.0,1.0,NF,0,NF,0,2,train
4,NaN,NaN,13.392406,7.082649,CMR,NaN,0,12,NaN,NaN,NaN,0,0,NaN,0,0,0,0,0,0,NaN,NaN,NaN,NaN,phase_II,1048656.0,1048656.0,POINT(13.392406 7.082649),290252.0,non,0.0,NF,NaN,NaN,12.0,NaN,2.0,1.0,NF,0,NF,0,2,train

In [421]:
# Print summaries
split_data['split'].value_counts(dropna=False)

split
train    5756
val      2477
Name: count, dtype: int64

In [422]:
pd.pivot_table(split_data,values='point_id',index=['Ref_LCover'],columns=['split'],aggfunc="count")

split       train  val
Ref_LCover
1             742  332
2              39   15
3             158   70
4             131   59
7              10    3
8              36   15
9             371  158
10             25   12
11            291  114
12           1691  739
13            306  121
14             24    9
15            392  176
16            206   83
17             87   36
18             11    4

#### Export

In [423]:
# export merged phase I and II data
all_ceo_data =  ceo_phase_I_II_out
merged_ceo.to_csv(all_ceo_data,index_label='ID')
stable_rows.to_csv(ceo_phase_I_II_stable_out,index_label='ID')

In [424]:
# export only stable data with training and validation split
split_data_train = split_data[(split_data['split'] == 'train')]
split_data.to_csv(ceo_phase_I_II_stable_out_train,index_label='ID')

In [425]:
# export only stable data with training and validation split
split_data_val = split_data[(split_data['split'] == 'val')]
split_data_val.to_csv(ceo_phase_I_II_stable_out_val,index_label='ID')