![title](../images/header.png)

Merging CEO data (phase I 2015-2020) and phase II (2015-2022) for training with calibration and validation split
-------
This notebook merges validated data from the stratified random CEO data (2015-2022) with ceo data from phase II (2015-2022)
For more information contact aurelie.shapiro@fao.org or remi.dannunzio@fao.org

this script merges multiple ceo files and data from CAFI phase I and phase II
you can use the last section to split CEO data into proportions of training and validation
in the parameters you will select your CEO clean files (from CAFI DDD eSBAE merge and clean CEO data)

#### first install libraries and packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# Set the display option to a large value to prevent text wrapping
pd.set_option('display.max_colwidth', None)

#### merge multiple CEO files and combine columns

### parameters

In [14]:
# COD COG CMR GAB EQG CAF
ISO = 'EQG'

In [2]:
# clean ceo data from script 05d
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/GAB/GAB_all_ceo_1522_clean.csv')
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/DRC/DRC_all_ceo_1522_clean.csv')
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/EQG/EQG_all_ceo_1522_clean.csv')
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/COG/COG_all_ceo_1522_1622_clean.csv',low_memory=False)
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/CAR/CAR_all_ceo_1522_clean.csv',low_memory=False)
ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/EQG/EQG_all_ceo_2015_2023_clean.csv', low_memory=False)
#ceo_phase_II = pd.read_csv('/home/sepal-user/module_results/esbae/CMR/CMR_all_ceo_1522_clean.csv',low_memory=False)

In [3]:
ceo_phase_II.head()

,ID,plotid,sampleid,lon,lat,sample_geom,Ref_FNF_2015,Ref_Regeneration,Ref_Change_1522,Ref_Change_Type_1522,ArtFor,ArtMine,InfraR,Urb,IndFor,Other,Other_Desc,IndMine,IndAg,ArtAg,Ref_Year_1522,Ref_NFtype_2015,Ref_Ftype_2015,collection,interpreted,Ref_Change_Year_1522,Ref_LCover_2015,Def2016,Def2017,Def2018,Def2019,Def2020,Def2021,Def2022,Deg2016,Deg2017,Deg2018,Deg2019,Deg2020,Deg2021,Deg2022,Defall,Degall,Stable,NF,sampling,Ref_FNF_2022,Ref_Change_2023,Ref_Change_Type_2023,Ref_Year_2023,Ref_NFtype_2022,Ref_Ftype_2022,Ref_Change_Year_2023,Ref_LCover_2022,Def2023,Deg2023,Ref_LCover,Ref_FNF,Ref_Change_Type,Ref_Change_Year,ISO
0,0,45,45,8.460650,3.453988,POINT(8.46065 3.453988),1.0,NaN,0.0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,NaN,1.0,coll_1522_1,1,Stable,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1,0,ceo_1522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1.0,1.0,Stable,Stable,EQG
1,1,65,65,8.431363,3.357773,POINT(8.431363 3.357773),1.0,NaN,0.0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,NaN,1.0,coll_1522_1,1,Stable,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1,0,ceo_1522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1.0,1.0,Stable,Stable,EQG
2,2,117,117,8.441585,3.319245,POINT(8.441585 3.319245),1.0,NaN,0.0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,NaN,1.0,coll_1522_1,1,Stable,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1,0,ceo_1522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1.0,1.0,Stable,Stable,EQG
3,3,108,108,8.490696,3.434682,POINT(8.490696 3.434682),1.0,NaN,0.0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,NaN,1.0,coll_1522_1,1,Stable,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1,0,ceo_1522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1.0,1.0,Stable,Stable,EQG
4,4,122,122,8.466201,3.367339,POINT(8.466201 3.367339),1.0,NaN,0.0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,NaN,1.0,coll_1522_1,1,Stable,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1,0,ceo_1522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1.0,1.0,Stable,Stable,EQG

In [4]:
phase_II_columns = ceo_phase_II.columns.tolist()
phase_II_columns

['ID',
 'plotid',
 'sampleid',
 'lon',
 'lat',
 'sample_geom',
 'Ref_FNF_2015',
 'Ref_Regeneration',
 'Ref_Change_1522',
 'Ref_Change_Type_1522',
 'ArtFor',
 'ArtMine',
 'InfraR',
 'Urb',
 'IndFor',
 'Other',
 'Other_Desc',
 'IndMine',
 'IndAg',
 'ArtAg',
 'Ref_Year_1522',
 'Ref_NFtype_2015',
 'Ref_Ftype_2015',
 'collection',
 'interpreted',
 'Ref_Change_Year_1522',
 'Ref_LCover_2015',
 'Def2016',
 'Def2017',
 'Def2018',
 'Def2019',
 'Def2020',
 'Def2021',
 'Def2022',
 'Deg2016',
 'Deg2017',
 'Deg2018',
 'Deg2019',
 'Deg2020',
 'Deg2021',
 'Deg2022',
 'Defall',
 'Degall',
 'Stable',
 'NF',
 'sampling',
 'Ref_FNF_2022',
 'Ref_Change_2023',
 'Ref_Change_Type_2023',
 'Ref_Year_2023',
 'Ref_NFtype_2022',
 'Ref_Ftype_2022',
 'Ref_Change_Year_2023',
 'Ref_LCover_2022',
 'Def2023',
 'Deg2023',
 'Ref_LCover',
 'Ref_FNF',
 'Ref_Change_Type',
 'Ref_Change_Year',
 'ISO']

In [5]:
ceo_phase_II['interpreted'].value_counts(dropna=False)

interpreted
1    4884
Name: count, dtype: int64

In [6]:
# output file names
# CEO phase I and phase II data
ceo_phase_I_II_out =  '/home/sepal-user/module_results/esbae/EQG/EQG_ceo_1523_phase_I_II.csv'
ceo_phase_I_II_stable_out = '/home/sepal-user/module_results/esbae/EQG/EQG_ceo_1523_phase_I_II_stable.csv'
# stable data split into training and validation
ceo_phase_I_II_stable_out_train = '/home/sepal-user/module_results/esbae/EQG/EQG_all_ceo_1523_phaseI_II_stable_train.csv'
ceo_phase_I_II_stable_out_val = '/home/sepal-user/module_results/esbae/EQG/EQG_all_ceo_1523_phaseI_II_stable_val.csv'

#### CEO phase I data (2015-2020)
##### this file is downloaded from git: https://github.com/aurelgrooves/CAFI_DDD

In [9]:
ceo_phase_I = pd.read_csv('/home/sepal-user/CAFI_DDD/CAFI files/CAFI_all_ceo_validation_2015_2020_uniqueID.csv', low_memory=False)
ceo_phase_I.reset_index(inplace=True)
phase_I_columns = ceo_phase_I.columns.tolist()
phase_I_columns

['index',
 'plotid_orig',
 'CEO_PLOTID',
 'lon',
 'lat',
 'ISO',
 'CEO_Ref_Code',
 'Ref_FNF_2015',
 'Ref_LCover',
 'Ref_Change_Type_1520',
 'Ref_Year_1520',
 'countDrivers',
 'InfraR',
 'Urb',
 'ArtAg',
 'IndAg',
 'ArtFor',
 'IndFor',
 'ArtMine',
 'IndMine',
 'Other',
 'Source',
 'Ref_Change_Year_1520',
 'Change_Bin_1520',
 'UniqueID']

In [10]:
ceo_phase_I.head()

,index,plotid_orig,CEO_PLOTID,lon,lat,ISO,CEO_Ref_Code,Ref_FNF_2015,Ref_LCover,Ref_Change_Type_1520,Ref_Year_1520,countDrivers,InfraR,Urb,ArtAg,IndAg,ArtFor,IndFor,ArtMine,IndMine,Other,Source,Ref_Change_Year_1520,Change_Bin_1520,UniqueID
0,0,171,NaN,24.043094,6.731301,CAF,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,306
1,1,140,NaN,18.704676,8.068803,CAF,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,307
2,2,173,NaN,13.502083,6.592511,CMR,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,308
3,3,174,NaN,23.944998,7.158989,CAF,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,309
4,4,158,NaN,13.697197,8.096830,CMR,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,310

In [11]:
ceo_phase_I['ISO'].value_counts(dropna=False)

ISO
COD    6411
CMR    2442
CAF    2325
GAB    1124
COG     686
EQG     127
Name: count, dtype: int64

In [12]:
ceo_phase_I['interpreted'] = 1

In [15]:
ceo_phase_I_ISO = ceo_phase_I[ceo_phase_I['ISO'] == ISO]
len(ceo_phase_I_ISO)

127

In [16]:
ceo_phase_I_ISO['Ref_LCover'].value_counts(dropna=False)

Ref_LCover
1     82
3     13
7     12
15     8
14     7
8      3
18     2
Name: count, dtype: int64

In [17]:
ceo_phase_I_ISO['ArtAg'].value_counts(dropna=False)

ArtAg
0    112
1     15
Name: count, dtype: int64

In [18]:
# validation proportion
split = 0.3

### end of parameters

In [19]:
# number of validated points
len(ceo_phase_II)

4884

In [20]:
# number of validated points
len(ceo_phase_I_ISO)

127

In [22]:
#drop columns
columns_to_drop = [col for col in ceo_phase_II.columns if col.startswith('Def') or col.startswith('Deg')]
ceo_phase_II.drop(columns=columns_to_drop, inplace=True)
ceo_phase_II = ceo_phase_II.drop(['Stable','NF'], axis=1)

KeyError: "['Stable', 'NF'] not found in axis"

In [23]:
ceo_phase_I.head()

,index,plotid_orig,CEO_PLOTID,lon,lat,ISO,CEO_Ref_Code,Ref_FNF_2015,Ref_LCover,Ref_Change_Type_1520,Ref_Year_1520,countDrivers,InfraR,Urb,ArtAg,IndAg,ArtFor,IndFor,ArtMine,IndMine,Other,Source,Ref_Change_Year_1520,Change_Bin_1520,UniqueID,interpreted
0,0,171,NaN,24.043094,6.731301,CAF,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,306,1
1,1,140,NaN,18.704676,8.068803,CAF,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,307,1
2,2,173,NaN,13.502083,6.592511,CMR,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,308,1
3,3,174,NaN,23.944998,7.158989,CAF,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,309,1
4,4,158,NaN,13.697197,8.096830,CMR,12,0,12,NF,NaN,0,0,0,0,0,0,0,0,0,0,ceo,NF,0,310,1

In [24]:
ceo_phase_II.head()

,ID,plotid,sampleid,lon,lat,sample_geom,Ref_FNF_2015,Ref_Regeneration,Ref_Change_1522,Ref_Change_Type_1522,ArtFor,ArtMine,InfraR,Urb,IndFor,Other,Other_Desc,IndMine,IndAg,ArtAg,Ref_Year_1522,Ref_NFtype_2015,Ref_Ftype_2015,collection,interpreted,Ref_Change_Year_1522,Ref_LCover_2015,sampling,Ref_FNF_2022,Ref_Change_2023,Ref_Change_Type_2023,Ref_Year_2023,Ref_NFtype_2022,Ref_Ftype_2022,Ref_Change_Year_2023,Ref_LCover_2022,Ref_LCover,Ref_FNF,Ref_Change_Type,Ref_Change_Year,ISO
0,0,45,45,8.460650,3.453988,POINT(8.46065 3.453988),1.0,NaN,0.0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,NaN,1.0,coll_1522_1,1,Stable,1.0,ceo_1522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,Stable,Stable,EQG
1,1,65,65,8.431363,3.357773,POINT(8.431363 3.357773),1.0,NaN,0.0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,NaN,1.0,coll_1522_1,1,Stable,1.0,ceo_1522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,Stable,Stable,EQG
2,2,117,117,8.441585,3.319245,POINT(8.441585 3.319245),1.0,NaN,0.0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,NaN,1.0,coll_1522_1,1,Stable,1.0,ceo_1522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,Stable,Stable,EQG
3,3,108,108,8.490696,3.434682,POINT(8.490696 3.434682),1.0,NaN,0.0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,NaN,1.0,coll_1522_1,1,Stable,1.0,ceo_1522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,Stable,Stable,EQG
4,4,122,122,8.466201,3.367339,POINT(8.466201 3.367339),1.0,NaN,0.0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,NaN,1.0,coll_1522_1,1,Stable,1.0,ceo_1522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,Stable,Stable,EQG

#### merge phase II with phase I data

In [25]:
data_frames =[ceo_phase_I_ISO, ceo_phase_II]
# Source file names corresponding to each data frame
source_file = ['phase_I', 'phase_II']  # Replace with your file names

# Merge data frames and add a new column for source file name
merged_ceo = pd.concat([df.assign(sampling=source_file) for df, source_file in zip(data_frames, source_file)], ignore_index=True)

In [26]:
# Print or use the merged data frame
merged_ceo.reset_index(inplace=True)
merged_I_columns = merged_ceo.columns.tolist()
merged_I_columns

['level_0',
 'index',
 'plotid_orig',
 'CEO_PLOTID',
 'lon',
 'lat',
 'ISO',
 'CEO_Ref_Code',
 'Ref_FNF_2015',
 'Ref_LCover',
 'Ref_Change_Type_1520',
 'Ref_Year_1520',
 'countDrivers',
 'InfraR',
 'Urb',
 'ArtAg',
 'IndAg',
 'ArtFor',
 'IndFor',
 'ArtMine',
 'IndMine',
 'Other',
 'Source',
 'Ref_Change_Year_1520',
 'Change_Bin_1520',
 'UniqueID',
 'interpreted',
 'sampling',
 'ID',
 'plotid',
 'sampleid',
 'sample_geom',
 'Ref_Regeneration',
 'Ref_Change_1522',
 'Ref_Change_Type_1522',
 'Other_Desc',
 'Ref_Year_1522',
 'Ref_NFtype_2015',
 'Ref_Ftype_2015',
 'collection',
 'Ref_Change_Year_1522',
 'Ref_LCover_2015',
 'Ref_FNF_2022',
 'Ref_Change_2023',
 'Ref_Change_Type_2023',
 'Ref_Year_2023',
 'Ref_NFtype_2022',
 'Ref_Ftype_2022',
 'Ref_Change_Year_2023',
 'Ref_LCover_2022',
 'Ref_FNF',
 'Ref_Change_Type',
 'Ref_Change_Year']

In [27]:
column_names = merged_ceo.columns.tolist()
# Print the list of column names
print(column_names)

['level_0', 'index', 'plotid_orig', 'CEO_PLOTID', 'lon', 'lat', 'ISO', 'CEO_Ref_Code', 'Ref_FNF_2015', 'Ref_LCover', 'Ref_Change_Type_1520', 'Ref_Year_1520', 'countDrivers', 'InfraR', 'Urb', 'ArtAg', 'IndAg', 'ArtFor', 'IndFor', 'ArtMine', 'IndMine', 'Other', 'Source', 'Ref_Change_Year_1520', 'Change_Bin_1520', 'UniqueID', 'interpreted', 'sampling', 'ID', 'plotid', 'sampleid', 'sample_geom', 'Ref_Regeneration', 'Ref_Change_1522', 'Ref_Change_Type_1522', 'Other_Desc', 'Ref_Year_1522', 'Ref_NFtype_2015', 'Ref_Ftype_2015', 'collection', 'Ref_Change_Year_1522', 'Ref_LCover_2015', 'Ref_FNF_2022', 'Ref_Change_2023', 'Ref_Change_Type_2023', 'Ref_Year_2023', 'Ref_NFtype_2022', 'Ref_Ftype_2022', 'Ref_Change_Year_2023', 'Ref_LCover_2022', 'Ref_FNF', 'Ref_Change_Type', 'Ref_Change_Year']

In [28]:
#drop columns
merged_ceo = merged_ceo.drop(['level_0','index','ID'], axis=1)

In [29]:
# only if you DON'T have 2023 data, then skip
# Create a new column 'Stable' with initial value 0
merged_ceo['Stable_Forest'] = 0

# Set 'Stable' to 1 where either 'Ref_Change_Type_1520' or 'Ref_Change_Type_1522' is 'Stable'
merged_ceo.loc[(merged_ceo['Ref_Change_Type_1520'] == 'Stable') | (merged_ceo['Ref_Change_Type_1522'] == 'Stable'), 'Stable_Forest'] = 1

# Display value counts of 'Stable' column
print(merged_ceo['Stable_Forest'].value_counts(dropna=False))

Stable_Forest
1    3365
0    1646
Name: count, dtype: int64

In [33]:
# only if you have 2023 data otherwise skip
# Create a new column 'Stable' with initial value 0
merged_ceo['Stable_Forest'] = 0

# Set 'Stable' to 1 where either 'Ref_Change_Type_1520' or 'Ref_Change_Type_1522' is 'Stable'
merged_ceo.loc[(merged_ceo['Ref_Change_Type_1520'] == 'Stable') | (merged_ceo['Ref_Change_Type_1522'] == 'Stable') | (merged_ceo['Ref_Change_Type_2023'] == 'Stable'), 'Stable_Forest'] = 1

# Display value counts of 'Stable' column
print(merged_ceo['Stable_Forest'].value_counts(dropna=False))

Stable_Forest
1    3725
0    1286
Name: count, dtype: int64

In [34]:
# Create a new column 'Ref Change Type' with initial value 0
merged_ceo['Ref_Change_Type'] = 0

In [566]:
# NO 2023 data
merged_ceo['Ref_Change_Type'] = merged_ceo['Ref_Change_Type_1520'].fillna(merged_ceo['Ref_Change_Type_1522'])

In [37]:
# with 2023 data
merged_ceo['Ref_Change_Type'] = merged_ceo['Ref_Change_Type_1520'].fillna(merged_ceo['Ref_Change_Type_1522'].fillna(merged_ceo['Ref_Change_Type_2023']))

In [38]:
print(merged_ceo['Ref_Change_Type'].value_counts(dropna=False))

Ref_Change_Type
Stable    3725
NF         926
Def        215
Deg        145
Name: count, dtype: int64

In [39]:
merged_ceo['Ref_Change_Bin'] = merged_ceo['Ref_Change_Type'].apply(lambda x:1 if x in ['Def','Deg'] else 0)
merged_ceo['Ref_Change_Bin'].value_counts(dropna=False)

Ref_Change_Bin
0    4651
1     360
Name: count, dtype: int64

In [40]:
merged_ceo['Ref_LCover'].value_counts(dropna=False)

Ref_LCover
1.0     2511
3.0      906
2.0      432
15.0     364
16.0     238
17.0     166
7.0       73
9.0       56
14.0      51
18.0      49
10.0      35
8.0       31
NaN       31
4.0       30
13.0      18
11.0      11
12.0       9
Name: count, dtype: int64

In [43]:
#create a new column for forest:1, non-forest:2, water: 3
# Define the conditions
conditions = [
    (merged_ceo['Ref_LCover'] >= 1) & (merged_ceo['Ref_LCover'] <= 11),
    (merged_ceo['Ref_LCover'] >= 12) & (merged_ceo['Ref_LCover'] <= 17)|(merged_ceo['Ref_LCover'] == 19) ,
    (merged_ceo['Ref_LCover'] == 18)
]

# Define the values to assign for each condition
values = [1, 2, 3]

# Use numpy.select() to assign values based on conditions
merged_ceo['Ref_FNFW'] = np.select(conditions, values, default=np.nan)
merged_ceo['Ref_FNFW'] = merged_ceo['Ref_FNFW'].astype(float)

merged_ceo['Ref_FNFW'].value_counts(dropna=False)

Ref_FNFW
1.0    4085
2.0     846
3.0      49
NaN      31
Name: count, dtype: int64

#### split stable data into training and calibration for land cover classification

In [45]:
# Filter rows where 'Stable' equals 1
stable_rows = merged_ceo[(merged_ceo['Ref_Change_Bin'] == 0)]

In [46]:
stable_rows.head()

,plotid_orig,CEO_PLOTID,lon,lat,ISO,CEO_Ref_Code,Ref_FNF_2015,Ref_LCover,Ref_Change_Type_1520,Ref_Year_1520,countDrivers,InfraR,Urb,ArtAg,IndAg,ArtFor,IndFor,ArtMine,IndMine,Other,Source,Ref_Change_Year_1520,Change_Bin_1520,UniqueID,interpreted,sampling,plotid,sampleid,sample_geom,Ref_Regeneration,Ref_Change_1522,Ref_Change_Type_1522,Other_Desc,Ref_Year_1522,Ref_NFtype_2015,Ref_Ftype_2015,collection,Ref_Change_Year_1522,Ref_LCover_2015,Ref_FNF_2022,Ref_Change_2023,Ref_Change_Type_2023,Ref_Year_2023,Ref_NFtype_2022,Ref_Ftype_2022,Ref_Change_Year_2023,Ref_LCover_2022,Ref_FNF,Ref_Change_Type,Ref_Change_Year,Stable_Forest,Ref_Change_Bin,Ref_FNFW
0,145.0,NaN,10.562436,1.001577,EQG,1.0,1.0,1.0,Stable,NaN,0.0,0,0,0,0,0,0,0,0,0,ceo,Stable,0.0,124.0,1,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,NaN,1,0,1.0
1,196.0,NaN,11.246683,1.284815,EQG,1.0,1.0,1.0,Stable,NaN,0.0,0,0,0,0,0,0,0,0,0,ceo,Stable,0.0,161.0,1,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,NaN,1,0,1.0
2,317.0,NaN,10.199157,2.012451,EQG,1.0,1.0,1.0,Stable,NaN,0.0,0,0,0,0,0,0,0,0,0,ceo,Stable,0.0,185.0,1,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,NaN,1,0,1.0
3,236.0,NaN,10.985543,1.123927,EQG,1.0,1.0,1.0,Stable,NaN,0.0,0,0,0,0,0,0,0,0,0,ceo,Stable,0.0,216.0,1,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,NaN,1,0,1.0
5,8437.0,282,9.549945,1.335211,EQG,1.0,1.0,1.0,Stable,NaN,0.0,0,0,0,0,0,0,0,0,0,ceo,Stable,0.0,599.0,1,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,NaN,1,0,1.0

In [47]:
# Define an empty DataFrame to store the split data
split_data = pd.DataFrame()

# Iterate over unique values in 'landcover' column
for landcover_value in stable_rows['Ref_LCover'].unique():
    # Filter rows for current landcover value
    landcover_rows = stable_rows[stable_rows['Ref_LCover'] == landcover_value]
    
    # Check if there is enough data to split
    if len(landcover_rows) > 1:
        # Split data into training and validation sets
        train_data, val_data = train_test_split(landcover_rows, test_size=split, random_state=42)
        
        # Add 'Split' column and assign 'train' or 'val' based on split
        train_data['split'] = 'train'
        val_data['split'] = 'val'
        
        # Concatenate data to the split_data DataFrame
        split_data = pd.concat([split_data, train_data, val_data], ignore_index=True)
    else:
        # Not enough data for splitting, assign all data as calibration data
        landcover_rows['split'] = 'train'
        split_data = pd.concat([split_data, landcover_rows], ignore_index=True)

split_data.head()

,plotid_orig,CEO_PLOTID,lon,lat,ISO,CEO_Ref_Code,Ref_FNF_2015,Ref_LCover,Ref_Change_Type_1520,Ref_Year_1520,countDrivers,InfraR,Urb,ArtAg,IndAg,ArtFor,IndFor,ArtMine,IndMine,Other,Source,Ref_Change_Year_1520,Change_Bin_1520,UniqueID,interpreted,sampling,plotid,sampleid,sample_geom,Ref_Regeneration,Ref_Change_1522,Ref_Change_Type_1522,Other_Desc,Ref_Year_1522,Ref_NFtype_2015,Ref_Ftype_2015,collection,Ref_Change_Year_1522,Ref_LCover_2015,Ref_FNF_2022,Ref_Change_2023,Ref_Change_Type_2023,Ref_Year_2023,Ref_NFtype_2022,Ref_Ftype_2022,Ref_Change_Year_2023,Ref_LCover_2022,Ref_FNF,Ref_Change_Type,Ref_Change_Year,Stable_Forest,Ref_Change_Bin,Ref_FNFW,split
0,NaN,NaN,8.659548,3.549884,EQG,NaN,1.0,1.0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,1,phase_II,24428.0,24428.0,POINT(8.659548 3.549884),NaN,0.0,Stable,NaN,NaN,NaN,1.0,coll_1522_2,Stable,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Stable,Stable,1,0,1.0,train
1,NaN,NaN,8.575533,3.424908,EQG,NaN,1.0,1.0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,1,phase_II,498.0,498.0,POINT(8.575533 3.424908),NaN,0.0,Stable,NaN,NaN,NaN,1.0,coll_1522_1,Stable,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Stable,Stable,1,0,1.0,train
2,NaN,NaN,10.743111,1.419391,EQG,NaN,1.0,1.0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,1,phase_II,44585.0,44585.0,POINT(10.743111 1.419391),NaN,0.0,Stable,NaN,NaN,NaN,1.0,coll_1522_2,Stable,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Stable,Stable,1,0,1.0,train
3,180194.0,6017,10.589116,1.324701,EQG,1.0,1.0,1.0,Stable,NaN,0.0,0,0,0,0,0,0,0,0,0,ceo,Stable,0.0,6509.0,1,phase_I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,NaN,1,0,1.0,train
4,NaN,NaN,10.648704,1.409757,EQG,NaN,1.0,1.0,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,1,phase_II,39772.0,39772.0,POINT(10.648704 1.409757),NaN,0.0,Stable,NaN,NaN,NaN,1.0,coll_1522_2,Stable,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Stable,Stable,1,0,1.0,train

In [48]:
# Print summaries
split_data['split'].value_counts(dropna=False)

split
train    3226
val      1394
Name: count, dtype: int64

In [50]:
pd.pivot_table(split_data,values='plotid',index=['Ref_LCover'],columns=['split'],aggfunc="count")

split       train  val
Ref_LCover
1.0          1636  708
2.0           293  126
3.0           468  202
4.0            19    9
7.0            44   17
8.0            18    8
9.0            38   17
10.0           16    8
11.0            7    4
12.0            6    3
13.0           12    6
14.0           31   13
15.0          250  106
16.0          166   72
17.0          116   50
18.0           32   15

#### Export

In [51]:
# export merged phase I and II data
all_ceo_data =  ceo_phase_I_II_out
merged_ceo.to_csv(all_ceo_data,index_label='ID')
stable_rows.to_csv(ceo_phase_I_II_stable_out,index_label='ID')

In [52]:
# export only stable data with training and validation split
split_data_train = split_data[(split_data['split'] == 'train')]
split_data.to_csv(ceo_phase_I_II_stable_out_train,index_label='ID')

In [53]:
# export only stable data with training and validation split
split_data_val = split_data[(split_data['split'] == 'val')]
split_data_val.to_csv(ceo_phase_I_II_stable_out_val,index_label='ID')