![title](../images/header.png)

Merging CEO data phase II (2023)
-------
This notebook merges validated data from different CEO CAFI projects for 2023
###### For more information contact aurelie.shapiro@fao.org or remi.dannunzio@fao.org

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# Set the display option to a large value to prevent text wrapping
pd.set_option('display.max_colwidth', None)

## Enter parameters

In [2]:
#identifier for country 
# COD COG CMR GAB EQG CAF
iso = 'CMR'

### 1. Read all CEO sample files
download your CEO sample files from collect.earth and upload to SEPAL using FileZilla.
add as many files as you have projects

In [3]:
#ceo1 = pd.read_csv('/home/sepal-user/module_results/esbae/GAB/ceo-CAFI-DDD-GAB-TNT-2023-collection-1-sample-data.csv')
#ceo2 = pd.read_csv('/home/sepal-user/module_results/esbae/GAB/ceo-CAFI-DDD-GAB-TNT-2023-collection-2-sample-data.csv')
#ceo3 = pd.read_csv('/home/sepal-user/module_results/esbae/GAB/ceo-CAFI-DDD-GAB-TNT-2023-collection-3-sample-data.csv')

#ceo1 = pd.read_csv('/home/sepal-user/module_results/esbae/CAR/ceo-CAFI-DDD-RCA-TNT-2023-collection-1-sample-data.csv')
#ceo2 = pd.read_csv('/home/sepal-user/module_results/esbae/CAR/ceo-CAFI-DDD-RCA-TNT-2023-collection-2-sample-data.csv')
#ceo3 = pd.read_csv('/home/sepal-user/module_results/esbae/CAR/ceo-CAFI-DDD-RCA-TNT-2023-collection-3-sample-data.csv')

#ceo1 = pd.read_csv('/home/sepal-user/module_results/esbae/EQG/ceo-CAFI-DDD-EQG-TNT-2023-collection-1-sample-data.csv')
#ceo2 = pd.read_csv('/home/sepal-user/module_results/esbae/EQG/ceo-CAFI-DDD-EQG-TNT-2023-collection-2-sample-data.csv')
#ceo3 = pd.read_csv('/home/sepal-user/module_results/esbae/EQG/ceo-CAFI-DDD-EQG-TNT-2023-collection-3-sample-data.csv')

#ceo1 = pd.read_csv('/home/sepal-user/module_results/esbae/DRC/ceo-CAFI-DDD-RDC-TNT-2023-collection-1-sample-data.csv')
#ceo2 = pd.read_csv('/home/sepal-user/module_results/esbae/DRC/ceo-CAFI-DDD-RDC-TNT-2023-collection-2-sample-data.csv')
#ceo3 = pd.read_csv('/home/sepal-user/module_results/esbae/DRC/ceo-CAFI-DDD-RDC-TNT-2023-collection-3-sample-data.csv')
#ceo4 = pd.read_csv('/home/sepal-user/module_results/esbae/DRC/ceo-CAFI-DDD-RDC-TNT-2023-collection-4-sample-data.csv')
#ceo5 = pd.read_csv('/home/sepal-user/module_results/esbae/DRC/ceo-CAFI-DDD-RDC-TNT-2023-collection-5-sample-data.csv')
#ceo6 = pd.read_csv('/home/sepal-user/module_results/esbae/DRC/ceo-CAFI-DDD-RDC-TNT-2023-collection-6-sample-data.csv')
#ceo7 = pd.read_csv('/home/sepal-user/module_results/esbae/DRC/ceo-CAFI-DDD-RDC-TNT-2023-whisp-coll1-sample-data.csv')

ceo1 = pd.read_csv('/home/sepal-user/module_results/esbae/CMR/ceo-CAFI-DDD-CMR-TNT-2023-collection-1-sample-data.csv')
ceo2 = pd.read_csv('/home/sepal-user/module_results/esbae/CMR/ceo-CAFI-DDD-CMR-TNT-2023-collection-2-sample-data.csv')
ceo3 = pd.read_csv('/home/sepal-user/module_results/esbae/CMR/ceo-CAFI-DDD-CMR-TNT-2023-collection-3-sample-data.csv')
ceo4 = pd.read_csv('/home/sepal-user/module_results/esbae/CMR/ceo-CAFI-DDD-CMR-TNT-2023-collection-4-sample-data.csv')
ceo5 = pd.read_csv('/home/sepal-user/module_results/esbae/CMR/ceo-CAFI-DDD-CMR-TNT-2023-collection-5-sample-data.csv')
ceo6 = pd.read_csv('/home/sepal-user/module_results/esbae/CMR/ceo-CAFI-DDD-CMR-TNT-2023-collection-6-sample-data.csv')

make a list of the ceo files for processing

In [4]:
#depends on how many files you have
ceo_files = [ceo1, ceo2, ceo3, ceo4, ceo5, ceo6]
# if you have 5 files
#ceo_files = [ceo1, ceo2, ceo3, ceo4,ceo5]
# if you have 3 files
#ceo_files = [ceo1, ceo2, ceo3]
# if you have 2 files
#ceo_files = [ceo1,ceo2]
# if you have 1 file
#ceo_files = [ceo1]

In [5]:
ceo1['collection'] = 'coll_2023_1'
ceo2['collection'] = 'coll_2023_2'
ceo3['collection'] = 'coll_2023_3'
ceo4['collection'] = 'coll_2023_4'
ceo5['collection'] = 'coll_2023_5'
ceo6['collection'] = 'coll_2023_6'
#ceo7['collection'] = 'whisp_2023_1'

In [6]:
# output file  CEO validated data file with select columns
ceo_data_out =  '/home/sepal-user/module_results/esbae/CMR/CMR_all_ceo_2023_clean.csv'

### end of parameters

In [7]:
column_names = ceo3.columns.tolist()
# Print the list of column names
print(column_names)

['plotid', 'sampleid', 'sample_internal_id', 'lon', 'lat', 'email', 'flagged', 'collection_time', 'analysis_duration', 'imagery_title', 'imagery_attributions', 'sample_geom', 'pl_index', 'pl_chgprob', 'pl_maxforprob', 'pl_strata', 'forêt ou non-forêt en 2022', "Y'a t'il de la régéneration", 'Changement en 2023', 'Type de Changement 2023', 'Exploitation forestière artisanale (<5ha)', 'Activité minière artisanale', 'Infrastructure routière', 'Infrastructure d’urbanisation ou habitations', 'Exploitation forestière industrielle (>5ha)', 'Autre moteur', 'Descriptif autre moteur', 'Activité minière industrielle', 'Agriculture industrielle', 'Agriculture paysanne', 'Année de Changement', 'Type de non-forêt en 2022', 'Type de forêt en 2022', 'Commentaires', 'collection']

##### add a column named "interpreted" which = 1 when the point has been validated in CEO, otherwise 0
count the number of validated points per ceo file
replace forest and non-forest types with codes

In [8]:
# List to store the modified DataFrames
modified_ceo_files = []

# Initialize collection counter
collection_counter = 1

for i, ceo in enumerate(ceo_files):
       
    # Sort the DataFrame by 'date' in descending order
    ceo.sort_values(by='collection_time', ascending=True, inplace=True)

    # Remove duplicates keeping the last occurrence (the most recent date)
    ceo.drop_duplicates(subset='sample_geom', keep='first', inplace=True)

    # Reset the index
    ceo.reset_index(drop=True, inplace=True)
       
    # Add 'interpreted' column with 1 when 'email' is not null, otherwise 0
    ceo['interpreted'] = np.where(ceo['email'].notna(), 1, 0)
    
    # Calculate total count for each 'interpreted' value
    interpreted_counts = ceo['interpreted'].value_counts().to_dict()
    
    # Append the modified DataFrame to the list
    modified_ceo_files.append(ceo)
    
    # Print count for the current DataFrame
    print(f"ceo {i + 1} # of validated points: {interpreted_counts.get(1, 0)}, # of not validated points: {interpreted_counts.get(0, 0)}")

# Concatenate the modified DataFrames into one merged DataFrame
merged_ceo = pd.concat(modified_ceo_files, ignore_index=True)


# Specify the columns you want to keep in the merged DataFrame
columns_to_keep = ['plotid', 'sampleid', 'lon', 'lat', 'pl_strata',
                    'sample_geom', 'forêt ou non-forêt en 2022', "Y'a t'il de la régéneration", 
                    'Changement en 2023', 'Type de Changement 2023', 'Exploitation forestière artisanale (<5ha)', 
                    'Activité minière artisanale', 'Infrastructure routière', 'Infrastructure d’urbanisation ou habitations', 
                    'Exploitation forestière industrielle (>5ha)', 'Autre moteur', 'Descriptif autre moteur', 'Activité minière industrielle', 
                    'Agriculture industrielle', 'Agriculture paysanne', 'Type de non-forêt en 2022', 'Type de forêt en 2022', 'collection', 'interpreted']

# Select only the specified columns
merged_ceo = merged_ceo[columns_to_keep]

# Create a dictionary to map old column names to new column names
column_mapping = {
    'forêt ou non-forêt en 2022': 'Ref_FNF_2022', 
    "Y'a t'il de la régéneration": 'Ref_Regeneration',
    'Changement en 2023': 'Ref_Change_2023', 
    'Type de Changement 2023': 'Ref_Change_Type_2023', 
    'Exploitation forestière artisanale (<5ha)': 'ArtFor',
    'Activité minière artisanale': 'ArtMine',
    'Infrastructure routière': 'InfraR', 
    'Infrastructure d’urbanisation ou habitations': 'Urb',
    'Exploitation forestière industrielle (>5ha)':'IndFor', 
    'Autre moteur': 'Other', 
    'Descriptif autre moteur': 'Other_Desc', 
    'Activité minière industrielle': 'IndMine', 
    'Agriculture industrielle': 'IndAg', 
    'Agriculture paysanne': 'ArtAg', 
    'Année de Changement': 'Ref_Year_2023', 
    'Type de non-forêt en 2022':'Ref_NFtype_2022', 
    'Type de forêt en 2022':'Ref_Ftype_2022',
    'pl_strata':'TNT_stratum'
    #add other columns as needed
    #,'NOM': 'Province' # DRC province
}

# Use the rename() method to rename the columns
merged_ceo = merged_ceo.rename(columns=column_mapping)

# Define the replacements as a dictionary
replace_dict = {
    'Ref_FNF_2022': {'non-forêt': '0', 'forêt': '1'},
    'Ref_Ftype_2022': {'1 - forêt dense': '1', '2 - forêt dense sèche': '2', '3 - forêt secondaire': '3','4 - forêt claire sèche': '4','7 - forêt mangrove': '7',
                 '8 - forêt marécageuse': '8', '9 - forêt galérie': '9','10 - plantation forestière': '10', '11- savane arborée': '11'},
    'Ref_NFtype_2022': {'12 - savane arbustive': '12', '13 - savane herbacée': '13', '14 - prairie aquatique': '14', '15 - sol nu végétation éparse': '15',
                  '16 - terres cultivées': '16', '17 - zone baties': '17', '18 - eau': '18'},
    'Ref_Change_2023': {'oui':'1','non':'0','':'0'},
    'ArtFor':{'oui':'1','non':'0','':'0'},
    'IndFor':{'oui':'1','non':'0','':'0'},
    'ArtAg':{'oui':'1','non':'0','':'0'},
    'IndAg':{'oui':'1','non':'0','':'0'},
    'ArtMine':{'oui':'1','non':'0','':'0'},
    'IndMine':{'oui':'1','non':'0','':'0'},
    'Urb':{'oui':'1','non':'0','':'0'},
    'InfraR':{'oui':'1','non':'0','':'0'},
    'Other':{'oui':'1','non':'0','':'0'}
}

# Use the replace() method to replace strings in specified columns
merged_ceo.replace(replace_dict, inplace=True)

columns_to_fill = ['Ref_Change_2023','ArtAg','ArtFor','IndFor','IndAg','ArtMine','IndMine','Urb','InfraR','Other']
# Set NaN values in the selected columns to 0
merged_ceo[columns_to_fill] = merged_ceo[columns_to_fill].fillna('0')

ceo 1 # of validated points: 497, # of not validated points: 0
ceo 2 # of validated points: 497, # of not validated points: 0
ceo 3 # of validated points: 202, # of not validated points: 0
ceo 4 # of validated points: 998, # of not validated points: 0
ceo 5 # of validated points: 304, # of not validated points: 0
ceo 6 # of validated points: 825, # of not validated points: 84

remove non validated points and remove duplicates

In [9]:
merged_ceo_interpreted = merged_ceo[merged_ceo['interpreted'] == 1]
len(merged_ceo_interpreted)

3323

In [10]:
# this might take some time
unique_check = merged_ceo_interpreted['sample_geom'].nunique() == len(merged_ceo_interpreted['sample_geom'])

# Print the result
if unique_check:
    print("All values are unique!")
else:
    print("F$%§!")

F$%§!

In [11]:
# Display rows where 'sample_geom' is duplicated
duplicates = merged_ceo_interpreted[merged_ceo_interpreted['sample_geom'].duplicated(keep=False)]

# Show duplicates
duplicates['collection'].value_counts(dropna=False)

collection
coll_2023_3    202
coll_2023_4    202
Name: count, dtype: int64

In [12]:
merged_ceo_interpreted = merged_ceo_interpreted.sort_values(by='collection', ascending=True)

# Remove duplicates keeping the last occurrence (the most recent date)
merged_ceo_nodup = merged_ceo_interpreted.drop_duplicates(subset='sample_geom', keep='first')

# Reset the index
merged_ceo_nodup = merged_ceo_nodup.reset_index(drop=True)

In [13]:
len(merged_ceo_nodup)

3121

In [14]:
merged_ceo_interpreted = merged_ceo_nodup

In [15]:
ceo_column_names = merged_ceo_interpreted.columns.tolist()
# Print the list of column names
print(ceo_column_names)

['plotid', 'sampleid', 'lon', 'lat', 'TNT_stratum', 'sample_geom', 'Ref_FNF_2022', 'Ref_Regeneration', 'Ref_Change_2023', 'Ref_Change_Type_2023', 'ArtFor', 'ArtMine', 'InfraR', 'Urb', 'IndFor', 'Other', 'Other_Desc', 'IndMine', 'IndAg', 'ArtAg', 'Ref_NFtype_2022', 'Ref_Ftype_2022', 'collection', 'interpreted']

In [16]:
merged_ceo_interpreted.head()

,plotid,sampleid,lon,lat,TNT_stratum,sample_geom,Ref_FNF_2022,Ref_Regeneration,Ref_Change_2023,Ref_Change_Type_2023,ArtFor,ArtMine,InfraR,Urb,IndFor,Other,Other_Desc,IndMine,IndAg,ArtAg,Ref_NFtype_2022,Ref_Ftype_2022,collection,interpreted
0,1,1,13.716960,4.010843,1.0,POINT(13.71695998 4.010842996),1,NaN,0,NaN,0,0,0,0,0,0,NaN,0,0,0,NaN,1,coll_2023_1,1
1,359,359,10.566568,3.631664,4.0,POINT(10.56656828 3.631664115),1,NaN,0,NaN,0,0,0,0,0,0,NaN,0,0,0,NaN,1,coll_2023_1,1
2,358,358,14.402375,8.204448,4.0,POINT(14.40237454 8.204448237),0,non,0,NaN,0,0,0,0,0,0,NaN,0,0,0,12,NaN,coll_2023_1,1
3,355,355,11.737432,5.282947,4.0,POINT(11.73743242 5.28294727),0,non,0,NaN,0,0,0,0,0,0,NaN,0,0,0,12,NaN,coll_2023_1,1
4,356,356,13.126497,8.137164,4.0,POINT(13.12649734 8.137164422),0,non,0,NaN,0,0,0,0,0,0,NaN,0,0,0,12,NaN,coll_2023_1,1

##### count points in different categories

In [17]:
merged_ceo_interpreted['interpreted'].value_counts(dropna=False)

interpreted
1    3121
Name: count, dtype: int64

In [18]:
pd.pivot_table(merged_ceo_interpreted,values='plotid',index=['Ref_Change_2023'],columns=['interpreted'],aggfunc="count")

interpreted         1
Ref_Change_2023
0                3022
1                  99

In [19]:
pd.pivot_table(merged_ceo_interpreted,values='plotid',index=['collection'],columns=['interpreted'],aggfunc="count")

interpreted    1
collection
coll_2023_1  497
coll_2023_2  497
coll_2023_3  202
coll_2023_4  796
coll_2023_5  304
coll_2023_6  825

In [20]:
merged_ceo_interpreted['Ref_FNF_2022'].value_counts(dropna=False)

Ref_FNF_2022
0    1611
1    1510
Name: count, dtype: int64

In [21]:
merged_ceo_interpreted['Ref_Change_Type_2023'].value_counts(dropna=False)

Ref_Change_Type_2023
NaN              3028
dégradation        68
déforestation      25
Name: count, dtype: int64

In [22]:
merged_ceo_interpreted['collection'].value_counts(dropna=False)

collection
coll_2023_6    825
coll_2023_4    796
coll_2023_1    497
coll_2023_2    497
coll_2023_5    304
coll_2023_3    202
Name: count, dtype: int64

##### create a LC type column

In [23]:
merged_ceo_interpreted = merged_ceo_interpreted.copy()
merged_ceo_interpreted.loc[:, 'Ref_LCover_2022'] = merged_ceo_interpreted['Ref_Ftype_2022'].fillna(merged_ceo_interpreted['Ref_NFtype_2022'])
merged_ceo_interpreted['Ref_LCover_2022'].value_counts(dropna=False)

Ref_LCover_2022
12    689
1     472
13    386
3     372
9     337
11    234
16    227
17    130
15    101
14     41
8      38
18     37
4      26
10     13
2      11
7       7
Name: count, dtype: int64

##### if there are any "je ne sais pas" the points need to be reviewed and corrected in CEO!

### 2. add new columns for change and year

clean up columns and replace values

In [24]:
def f(x):
  if x['Ref_FNF_2022'] == '0' : return 'NF'
  elif x['Ref_Change_Type_2023'] == 'déforestation': return 'Def'
  elif x['Ref_Change_Type_2023'] == 'dégradation' : return 'Deg'
  else: return 'Stable'

merged_ceo_interpreted.loc[:, 'Ref_Change_Type_2023'] = merged_ceo_interpreted.apply(f, axis=1)
merged_ceo_interpreted['Ref_Change_Type_2023'].value_counts()

Ref_Change_Type_2023
NF        1611
Stable    1417
Deg         68
Def         25
Name: count, dtype: int64

In [25]:
def y(x):
  if x['Ref_Change_Type_2023'] == 'Def': return 'Def2023'
  elif x['Ref_Change_Type_2023'] == 'Deg' : return 'Deg2023'
  elif x['Ref_Change_Type_2023'] == 'NF' : return 'NF'
  elif x['Ref_Change_Type_2023'] == 'Stable' : return 'Stable'
  else: return ''

merged_ceo_interpreted.loc[:,'Ref_Change_Year_2023'] = merged_ceo_interpreted.apply(y, axis=1)

annual_counts = merged_ceo_interpreted['Ref_Change_Year_2023'].value_counts()
annual_counts = annual_counts.sort_index()
print(annual_counts)

Ref_Change_Year_2023
Def2023      25
Deg2023      68
NF         1611
Stable     1417
Name: count, dtype: int64

In [26]:
# Define the new column based on conditions
merged_ceo_interpreted.loc[:,'Ref_Change_LCover_2023'] = merged_ceo_interpreted.apply(lambda row: f"{row['Ref_Change_Type_2023']}_{row['Ref_LCover_2022']}", axis=1)

In [27]:
merged_ceo_interpreted.loc[:,'Def2023'] = np.where(merged_ceo_interpreted['Ref_Change_Year_2023'] == 'Def2023', 1, 0)
merged_ceo_interpreted.loc[:,'Deg2023'] = np.where(merged_ceo_interpreted['Ref_Change_Year_2023'] == 'Deg2023', 1, 0)

In [28]:
merged_ceo_interpreted.loc[:,'Defall'] = np.where(merged_ceo_interpreted['Ref_Change_Type_2023'] == 'Def', 1, 0)
merged_ceo_interpreted.loc[:,'Degall'] = np.where(merged_ceo_interpreted['Ref_Change_Type_2023'] == 'Deg', 1, 0)

In [29]:
merged_ceo_interpreted.loc[:,'Stable'] = np.where(merged_ceo_interpreted['Ref_Change_Type_2023'] == 'Stable', 1, 0)
merged_ceo_interpreted.loc[:,'NF'] = np.where(merged_ceo_interpreted['Ref_Change_Type_2023'] == 'NF', 1, 0)

In [30]:
merged_ceo_interpreted.loc[:,'DensFor'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '1', 1, 0)
merged_ceo_interpreted.loc[:,'DensDryFor'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '2', 1, 0)
merged_ceo_interpreted.loc[:,'SecFor'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '3', 1, 0)
merged_ceo_interpreted.loc[:,'DryOpenFor'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '4', 1, 0)
#merged_ceo_interpreted['SubMont'] = np.where(merged_ceo_interpreted['Ref_LCover_2015'] == '5', 1, 0)
#merged_ceo_interpreted['MontFor'] = np.where(merged_ceo_interpreted['Ref_LCover_2015'] == '6', 1, 0)
merged_ceo_interpreted.loc[:,'Mangrove'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '7', 1, 0)
merged_ceo_interpreted.loc[:,'Swamp'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '8', 1, 0)
merged_ceo_interpreted.loc[:,'Gallery'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '9', 1, 0)
merged_ceo_interpreted.loc[:,'Plantation'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '10', 1, 0)
merged_ceo_interpreted.loc[:,'Woodland'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '11', 1, 0)
merged_ceo_interpreted.loc[:,'Shrubland'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '12', 1, 0)
merged_ceo_interpreted.loc[:,'Grassland'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '13', 1, 0)
merged_ceo_interpreted.loc[:,'Aquatic'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '14', 1, 0)
merged_ceo_interpreted.loc[:,'Bare'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '15', 1, 0)
merged_ceo_interpreted.loc[:,'Cultivated'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '16', 1, 0)
merged_ceo_interpreted.loc[:,'Builtup'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '17', 1, 0)
merged_ceo_interpreted.loc[:,'Water'] = np.where(merged_ceo_interpreted['Ref_LCover_2022'] == '18', 1, 0)

In [31]:
merged_ceo_interpreted.loc[:,'DensFor_Def'] = ((merged_ceo_interpreted['DensFor'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Def")).astype(int)
merged_ceo_interpreted.loc[:,'DensDryFor_Def'] = ((merged_ceo_interpreted['DensDryFor'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Def")).astype(int)
merged_ceo_interpreted.loc[:,'SecFor_Def'] = ((merged_ceo_interpreted['SecFor'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Def")).astype(int)
merged_ceo_interpreted.loc[:,'DryOpenFor_Def'] = ((merged_ceo_interpreted['DryOpenFor'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Def")).astype(int)
merged_ceo_interpreted.loc[:,'Mangrove_Def'] = ((merged_ceo_interpreted['Mangrove'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Def")).astype(int)
merged_ceo_interpreted.loc[:,'Swamp_Def'] = ((merged_ceo_interpreted['Swamp'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Def")).astype(int)
merged_ceo_interpreted.loc[:,'Gallery_Def'] = ((merged_ceo_interpreted['Gallery'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Def")).astype(int)
merged_ceo_interpreted.loc[:,'Plantation_Def'] = ((merged_ceo_interpreted['Plantation'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Def")).astype(int)
merged_ceo_interpreted.loc[:,'Woodland_Def'] = ((merged_ceo_interpreted['Woodland'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Def")).astype(int)

In [32]:
merged_ceo_interpreted.loc[:,'DensFor_Deg'] = ((merged_ceo_interpreted['DensFor'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Deg")).astype(int)
merged_ceo_interpreted.loc[:,'DensDryFor_Deg'] = ((merged_ceo_interpreted['DensDryFor'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Deg")).astype(int)
merged_ceo_interpreted.loc[:,'SecFor_Deg'] = ((merged_ceo_interpreted['SecFor'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Deg")).astype(int)
merged_ceo_interpreted.loc[:,'DryOpenFor_Deg'] = ((merged_ceo_interpreted['DryOpenFor'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Deg")).astype(int)
merged_ceo_interpreted.loc[:,'Mangrove_Deg'] = ((merged_ceo_interpreted['Mangrove'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Deg")).astype(int)
merged_ceo_interpreted.loc[:,'Swamp_Deg'] = ((merged_ceo_interpreted['Swamp'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Deg")).astype(int)
merged_ceo_interpreted.loc[:,'Gallery_Deg'] = ((merged_ceo_interpreted['Gallery'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Deg")).astype(int)
merged_ceo_interpreted.loc[:,'Plantation_Deg'] = ((merged_ceo_interpreted['Plantation'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Deg")).astype(int)
merged_ceo_interpreted.loc[:,'Woodland_Deg'] = ((merged_ceo_interpreted['Woodland'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Deg")).astype(int)

In [33]:
merged_ceo_interpreted.loc[:,'DensFor_Stable'] = ((merged_ceo_interpreted['DensFor'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Stable")).astype(int)
merged_ceo_interpreted.loc[:,'DensDryFor_Stable'] = ((merged_ceo_interpreted['DensDryFor'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Stable")).astype(int)
merged_ceo_interpreted.loc[:,'SecFor_Stable'] = ((merged_ceo_interpreted['SecFor'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Stable")).astype(int)
merged_ceo_interpreted.loc[:,'DryOpenFor_Stable'] = ((merged_ceo_interpreted['DryOpenFor'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Stable")).astype(int)
merged_ceo_interpreted.loc[:,'Mangrove_Stable'] = ((merged_ceo_interpreted['Mangrove'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Stable")).astype(int)
merged_ceo_interpreted.loc[:,'Swamp_Stable'] = ((merged_ceo_interpreted['Swamp'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Stable")).astype(int)
merged_ceo_interpreted.loc[:,'Gallery_Stable'] = ((merged_ceo_interpreted['Gallery'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Stable")).astype(int)
merged_ceo_interpreted.loc[:,'Plantation_Stable'] = ((merged_ceo_interpreted['Plantation'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Stable")).astype(int)
merged_ceo_interpreted.loc[:,'Woodland_Stable'] = ((merged_ceo_interpreted['Woodland'] == 1) & (merged_ceo_interpreted['Ref_Change_Type_2023'] == "Stable")).astype(int)

In [34]:
columns_to_convert = ['Deg2023','Def2023','Degall','Defall','Stable','NF',
'DensFor','DensDryFor','SecFor','DryOpenFor','Mangrove','Swamp','Gallery','Plantation','Woodland','Shrubland','Grassland','Aquatic','Bare','Cultivated','Builtup','Water',
'DensFor_Def','DensDryFor_Def','SecFor_Def','DryOpenFor_Def','Mangrove_Def','Swamp_Def','Gallery_Def','Plantation_Def','Woodland_Def',
'DensFor_Deg','DensDryFor_Deg','SecFor_Deg','DryOpenFor_Deg','Mangrove_Deg','Swamp_Deg','Gallery_Deg','Plantation_Deg','Woodland_Deg',
'DensFor_Stable','DensDryFor_Stable','SecFor_Stable','DryOpenFor_Stable','Mangrove_Stable','Swamp_Stable','Gallery_Stable','Plantation_Stable','Woodland_Stable']
merged_ceo_interpreted.loc[:,columns_to_convert] = merged_ceo_interpreted[columns_to_convert].fillna(0)

In [35]:
annual_counts.sum()

3121

In [36]:
pd.pivot_table(merged_ceo_interpreted,values='plotid',index=['Ref_Change_Type_2023'],columns=['interpreted'],aggfunc="count",margins=True,
                             margins_name='Total')

interpreted              1  Total
Ref_Change_Type_2023
Def                     25     25
Deg                     68     68
NF                    1611   1611
Stable                1417   1417
Total                 3121   3121

In [37]:
pd.pivot_table(merged_ceo_interpreted,values='plotid',index=['Woodland_Def'],columns=['interpreted'],aggfunc="count",margins=True,
                             margins_name='Total')

interpreted      1  Total
Woodland_Def
0             3120   3120
1                1      1
Total         3121   3121

In [38]:
# Create a matrix showing the number of matching values between two columns
matrix = pd.crosstab(merged_ceo_interpreted['Ref_LCover_2022'], merged_ceo_interpreted['Ref_Change_Type_2023'], rownames=['Ref_LCover'], colnames=['Ref_Change_Type'])

# Display the matrix
print(matrix)

Ref_Change_Type  Def  Deg   NF  Stable
Ref_LCover
1                  0    8    0     464
10                 0    2    0      11
11                 1    3    0     230
12                 0    0  689       0
13                 0    0  386       0
14                 0    0   41       0
15                 0    0  101       0
16                 0    0  227       0
17                 0    0  130       0
18                 0    0   37       0
2                  0    0    0      11
3                 17   49    0     306
4                  0    1    0      25
7                  1    0    0       6
8                  0    0    0      38
9                  6    5    0     326

In [39]:
merged_ceo_column_names = merged_ceo_interpreted.columns.tolist()
# Print the list of column names
print(merged_ceo_column_names)

['plotid', 'sampleid', 'lon', 'lat', 'TNT_stratum', 'sample_geom', 'Ref_FNF_2022', 'Ref_Regeneration', 'Ref_Change_2023', 'Ref_Change_Type_2023', 'ArtFor', 'ArtMine', 'InfraR', 'Urb', 'IndFor', 'Other', 'Other_Desc', 'IndMine', 'IndAg', 'ArtAg', 'Ref_NFtype_2022', 'Ref_Ftype_2022', 'collection', 'interpreted', 'Ref_LCover_2022', 'Ref_Change_Year_2023', 'Ref_Change_LCover_2023', 'Def2023', 'Deg2023', 'Defall', 'Degall', 'Stable', 'NF', 'DensFor', 'DensDryFor', 'SecFor', 'DryOpenFor', 'Mangrove', 'Swamp', 'Gallery', 'Plantation', 'Woodland', 'Shrubland', 'Grassland', 'Aquatic', 'Bare', 'Cultivated', 'Builtup', 'Water', 'DensFor_Def', 'DensDryFor_Def', 'SecFor_Def', 'DryOpenFor_Def', 'Mangrove_Def', 'Swamp_Def', 'Gallery_Def', 'Plantation_Def', 'Woodland_Def', 'DensFor_Deg', 'DensDryFor_Deg', 'SecFor_Deg', 'DryOpenFor_Deg', 'Mangrove_Deg', 'Swamp_Deg', 'Gallery_Deg', 'Plantation_Deg', 'Woodland_Deg', 'DensFor_Stable', 'DensDryFor_Stable', 'SecFor_Stable', 'DryOpenFor_Stable', 'Mangrove_Stable', 'Swamp_Stable', 'Gallery_Stable', 'Plantation_Stable', 'Woodland_Stable']

In [40]:
merged_ceo_interpreted.head()

,plotid,sampleid,lon,lat,TNT_stratum,sample_geom,Ref_FNF_2022,Ref_Regeneration,Ref_Change_2023,Ref_Change_Type_2023,ArtFor,ArtMine,InfraR,Urb,IndFor,Other,Other_Desc,IndMine,IndAg,ArtAg,Ref_NFtype_2022,Ref_Ftype_2022,collection,interpreted,Ref_LCover_2022,Ref_Change_Year_2023,Ref_Change_LCover_2023,Def2023,Deg2023,Defall,Degall,Stable,NF,DensFor,DensDryFor,SecFor,DryOpenFor,Mangrove,Swamp,Gallery,Plantation,Woodland,Shrubland,Grassland,Aquatic,Bare,Cultivated,Builtup,Water,DensFor_Def,DensDryFor_Def,SecFor_Def,DryOpenFor_Def,Mangrove_Def,Swamp_Def,Gallery_Def,Plantation_Def,Woodland_Def,DensFor_Deg,DensDryFor_Deg,SecFor_Deg,DryOpenFor_Deg,Mangrove_Deg,Swamp_Deg,Gallery_Deg,Plantation_Deg,Woodland_Deg,DensFor_Stable,DensDryFor_Stable,SecFor_Stable,DryOpenFor_Stable,Mangrove_Stable,Swamp_Stable,Gallery_Stable,Plantation_Stable,Woodland_Stable
0,1,1,13.716960,4.010843,1.0,POINT(13.71695998 4.010842996),1,NaN,0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,1,coll_2023_1,1,1,Stable,Stable_1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,359,359,10.566568,3.631664,4.0,POINT(10.56656828 3.631664115),1,NaN,0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,1,coll_2023_1,1,1,Stable,Stable_1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
2,358,358,14.402375,8.204448,4.0,POINT(14.40237454 8.204448237),0,non,0,NF,0,0,0,0,0,0,NaN,0,0,0,12,NaN,coll_2023_1,1,12,NF,NF_12,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,355,355,11.737432,5.282947,4.0,POINT(11.73743242 5.28294727),0,non,0,NF,0,0,0,0,0,0,NaN,0,0,0,12,NaN,coll_2023_1,1,12,NF,NF_12,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,356,356,13.126497,8.137164,4.0,POINT(13.12649734 8.137164422),0,non,0,NF,0,0,0,0,0,0,NaN,0,0,0,12,NaN,coll_2023_1,1,12,NF,NF_12,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [41]:
print(merged_ceo_interpreted.columns.values)

['plotid' 'sampleid' 'lon' 'lat' 'TNT_stratum' 'sample_geom'
 'Ref_FNF_2022' 'Ref_Regeneration' 'Ref_Change_2023'
 'Ref_Change_Type_2023' 'ArtFor' 'ArtMine' 'InfraR' 'Urb' 'IndFor' 'Other'
 'Other_Desc' 'IndMine' 'IndAg' 'ArtAg' 'Ref_NFtype_2022' 'Ref_Ftype_2022'
 'collection' 'interpreted' 'Ref_LCover_2022' 'Ref_Change_Year_2023'
 'Ref_Change_LCover_2023' 'Def2023' 'Deg2023' 'Defall' 'Degall' 'Stable'
 'NF' 'DensFor' 'DensDryFor' 'SecFor' 'DryOpenFor' 'Mangrove' 'Swamp'
 'Gallery' 'Plantation' 'Woodland' 'Shrubland' 'Grassland' 'Aquatic'
 'Bare' 'Cultivated' 'Builtup' 'Water' 'DensFor_Def' 'DensDryFor_Def'
 'SecFor_Def' 'DryOpenFor_Def' 'Mangrove_Def' 'Swamp_Def' 'Gallery_Def'
 'Plantation_Def' 'Woodland_Def' 'DensFor_Deg' 'DensDryFor_Deg'
 'SecFor_Deg' 'DryOpenFor_Deg' 'Mangrove_Deg' 'Swamp_Deg' 'Gallery_Deg'
 'Plantation_Deg' 'Woodland_Deg' 'DensFor_Stable' 'DensDryFor_Stable'
 'SecFor_Stable' 'DryOpenFor_Stable' 'Mangrove_Stable' 'Swamp_Stable'
 'Gallery_Stable' 'Plantation_Stable' 'Woodland_Stable']

In [42]:
merged_ceo_interpreted['Ref_Change_Year_2023'].value_counts(dropna=False)

Ref_Change_Year_2023
NF         1611
Stable     1417
Deg2023      68
Def2023      25
Name: count, dtype: int64

In [43]:
merged_ceo_interpreted.head()

,plotid,sampleid,lon,lat,TNT_stratum,sample_geom,Ref_FNF_2022,Ref_Regeneration,Ref_Change_2023,Ref_Change_Type_2023,ArtFor,ArtMine,InfraR,Urb,IndFor,Other,Other_Desc,IndMine,IndAg,ArtAg,Ref_NFtype_2022,Ref_Ftype_2022,collection,interpreted,Ref_LCover_2022,Ref_Change_Year_2023,Ref_Change_LCover_2023,Def2023,Deg2023,Defall,Degall,Stable,NF,DensFor,DensDryFor,SecFor,DryOpenFor,Mangrove,Swamp,Gallery,Plantation,Woodland,Shrubland,Grassland,Aquatic,Bare,Cultivated,Builtup,Water,DensFor_Def,DensDryFor_Def,SecFor_Def,DryOpenFor_Def,Mangrove_Def,Swamp_Def,Gallery_Def,Plantation_Def,Woodland_Def,DensFor_Deg,DensDryFor_Deg,SecFor_Deg,DryOpenFor_Deg,Mangrove_Deg,Swamp_Deg,Gallery_Deg,Plantation_Deg,Woodland_Deg,DensFor_Stable,DensDryFor_Stable,SecFor_Stable,DryOpenFor_Stable,Mangrove_Stable,Swamp_Stable,Gallery_Stable,Plantation_Stable,Woodland_Stable
0,1,1,13.716960,4.010843,1.0,POINT(13.71695998 4.010842996),1,NaN,0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,1,coll_2023_1,1,1,Stable,Stable_1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,359,359,10.566568,3.631664,4.0,POINT(10.56656828 3.631664115),1,NaN,0,Stable,0,0,0,0,0,0,NaN,0,0,0,NaN,1,coll_2023_1,1,1,Stable,Stable_1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
2,358,358,14.402375,8.204448,4.0,POINT(14.40237454 8.204448237),0,non,0,NF,0,0,0,0,0,0,NaN,0,0,0,12,NaN,coll_2023_1,1,12,NF,NF_12,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,355,355,11.737432,5.282947,4.0,POINT(11.73743242 5.28294727),0,non,0,NF,0,0,0,0,0,0,NaN,0,0,0,12,NaN,coll_2023_1,1,12,NF,NF_12,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,356,356,13.126497,8.137164,4.0,POINT(13.12649734 8.137164422),0,non,0,NF,0,0,0,0,0,0,NaN,0,0,0,12,NaN,coll_2023_1,1,12,NF,NF_12,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [44]:
merged_ceo_interpreted.loc[:,'ISO'] = iso

In [45]:
print(merged_ceo_interpreted.dtypes)

plotid                      int64
sampleid                    int64
lon                       float64
lat                       float64
TNT_stratum               float64
sample_geom                object
Ref_FNF_2022               object
Ref_Regeneration           object
Ref_Change_2023            object
Ref_Change_Type_2023       object
ArtFor                     object
ArtMine                    object
InfraR                     object
Urb                        object
IndFor                     object
Other                      object
Other_Desc                 object
IndMine                    object
IndAg                      object
ArtAg                      object
Ref_NFtype_2022            object
Ref_Ftype_2022             object
collection                 object
interpreted                 int64
Ref_LCover_2022            object
Ref_Change_Year_2023       object
Ref_Change_LCover_2023     object
Def2023                     int64
Deg2023                     int64
Defall                      int64
Degall                      int64
Stable                      int64
NF                          int64
DensFor                     int64
DensDryFor                  int64
SecFor                      int64
DryOpenFor                  int64
Mangrove                    int64
Swamp                       int64
Gallery                     int64
Plantation                  int64
Woodland                    int64
Shrubland                   int64
Grassland                   int64
Aquatic                     int64
Bare                        int64
Cultivated                  int64
Builtup                     int64
Water                       int64
DensFor_Def                 int64
DensDryFor_Def              int64
SecFor_Def                  int64
DryOpenFor_Def              int64
Mangrove_Def                int64
Swamp_Def                   int64
Gallery_Def                 int64
Plantation_Def              int64
Woodland_Def                int64
DensFor_Deg                 int64
DensDryFor_Deg              int64
SecFor_Deg                  int64
DryOpenFor_Deg              int64
Mangrove_Deg                int64
Swamp_Deg                   int64
Gallery_Deg                 int64
Plantation_Deg              int64
Woodland_Deg                int64
DensFor_Stable              int64
DensDryFor_Stable           int64
SecFor_Stable               int64
DryOpenFor_Stable           int64
Mangrove_Stable             int64
Swamp_Stable                int64
Gallery_Stable              int64
Plantation_Stable           int64
Woodland_Stable             int64
ISO                        object
dtype: object

### 4. export ceo data to one csv file

In [46]:
merged_ceo_interpreted.to_csv(ceo_data_out,index_label='ID')